-- This file was automatically generated.
module Graphics.OpenGL.Extension.OES.TextureCompressionAstc (
	-- * Extension Support
	  gl_OES_texture_compression_astc

	-- * GL_OES_texture_compression_astc
	, gl_COMPRESSED_RGBA_ASTC_10x10_KHR
	, gl_COMPRESSED_RGBA_ASTC_10x5_KHR
	, gl_COMPRESSED_RGBA_ASTC_10x6_KHR
	, gl_COMPRESSED_RGBA_ASTC_10x8_KHR
	, gl_COMPRESSED_RGBA_ASTC_12x10_KHR
	, gl_COMPRESSED_RGBA_ASTC_12x12_KHR
	, gl_COMPRESSED_RGBA_ASTC_3x3x3_OES
	, gl_COMPRESSED_RGBA_ASTC_4x3x3_OES
	, gl_COMPRESSED_RGBA_ASTC_4x4_KHR
	, gl_COMPRESSED_RGBA_ASTC_4x4x3_OES
	, gl_COMPRESSED_RGBA_ASTC_4x4x4_OES
	, gl_COMPRESSED_RGBA_ASTC_5x4_KHR
	, gl_COMPRESSED_RGBA_ASTC_5x4x4_OES
	, gl_COMPRESSED_RGBA_ASTC_5x5_KHR
	, gl_COMPRESSED_RGBA_ASTC_5x5x4_OES
	, gl_COMPRESSED_RGBA_ASTC_5x5x5_OES
	, gl_COMPRESSED_RGBA_ASTC_6x5_KHR
	, gl_COMPRESSED_RGBA_ASTC_6x5x5_OES
	, gl_COMPRESSED_RGBA_ASTC_6x6_KHR
	, gl_COMPRESSED_RGBA_ASTC_6x6x5_OES
	, gl_COMPRESSED_RGBA_ASTC_6x6x6_OES
	, gl_COMPRESSED_RGBA_ASTC_8x5_KHR
	, gl_COMPRESSED_RGBA_ASTC_8x6_KHR
	, gl_COMPRESSED_RGBA_ASTC_8x8_KHR
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_10x10_KHR
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_KHR
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_10x6_KHR
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_10x8_KHR
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_12x10_KHR
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_3x3x3_OES
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_4x3x3_OES
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_KHR
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x3_OES
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x4_OES
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4_KHR
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4x4_OES
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_KHR
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x4_OES
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x5_OES
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5_KHR
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5x5_OES
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x5_OES
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x6_OES
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_KHR
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_KHR
	, gl_COMPRESSED_SRGB8_ALPHA8_ASTC_8x8_KHR
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

import Graphics.OpenGL.Internal.Shared

gl_OES_texture_compression_astc :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_OES_texture_compression_astc = extGL 584

gl_COMPRESSED_RGBA_ASTC_3x3x3_OES :: GLenum
gl_COMPRESSED_RGBA_ASTC_3x3x3_OES = 0x93C0

gl_COMPRESSED_RGBA_ASTC_4x3x3_OES :: GLenum
gl_COMPRESSED_RGBA_ASTC_4x3x3_OES = 0x93C1

gl_COMPRESSED_RGBA_ASTC_4x4x3_OES :: GLenum
gl_COMPRESSED_RGBA_ASTC_4x4x3_OES = 0x93C2

gl_COMPRESSED_RGBA_ASTC_4x4x4_OES :: GLenum
gl_COMPRESSED_RGBA_ASTC_4x4x4_OES = 0x93C3

gl_COMPRESSED_RGBA_ASTC_5x4x4_OES :: GLenum
gl_COMPRESSED_RGBA_ASTC_5x4x4_OES = 0x93C4

gl_COMPRESSED_RGBA_ASTC_5x5x4_OES :: GLenum
gl_COMPRESSED_RGBA_ASTC_5x5x4_OES = 0x93C5

gl_COMPRESSED_RGBA_ASTC_5x5x5_OES :: GLenum
gl_COMPRESSED_RGBA_ASTC_5x5x5_OES = 0x93C6

gl_COMPRESSED_RGBA_ASTC_6x5x5_OES :: GLenum
gl_COMPRESSED_RGBA_ASTC_6x5x5_OES = 0x93C7

gl_COMPRESSED_RGBA_ASTC_6x6x5_OES :: GLenum
gl_COMPRESSED_RGBA_ASTC_6x6x5_OES = 0x93C8

gl_COMPRESSED_RGBA_ASTC_6x6x6_OES :: GLenum
gl_COMPRESSED_RGBA_ASTC_6x6x6_OES = 0x93C9

gl_COMPRESSED_SRGB8_ALPHA8_ASTC_3x3x3_OES :: GLenum
gl_COMPRESSED_SRGB8_ALPHA8_ASTC_3x3x3_OES = 0x93E0

gl_COMPRESSED_SRGB8_ALPHA8_ASTC_4x3x3_OES :: GLenum
gl_COMPRESSED_SRGB8_ALPHA8_ASTC_4x3x3_OES = 0x93E1

gl_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x3_OES :: GLenum
gl_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x3_OES = 0x93E2

gl_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x4_OES :: GLenum
gl_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x4_OES = 0x93E3

gl_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4x4_OES :: GLenum
gl_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4x4_OES = 0x93E4

gl_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x4_OES :: GLenum
gl_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x4_OES = 0x93E5

gl_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x5_OES :: GLenum
gl_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x5_OES = 0x93E6

gl_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5x5_OES :: GLenum
gl_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5x5_OES = 0x93E7

gl_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x5_OES :: GLenum
gl_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x5_OES = 0x93E8

gl_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x6_OES :: GLenum
gl_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x6_OES = 0x93E9