-- This file was automatically generated.
module Graphics.OpenGL.Profile.Core42 (
	-- * Graphics.OpenGL.Profile.Core42
	  module Graphics.OpenGL.Profile.Core41
	, glBindImageTexture
	, glDrawArraysInstancedBaseInstance
	, glDrawElementsInstancedBaseInstance
	, glDrawElementsInstancedBaseVertexBaseInstance
	, glDrawTransformFeedbackInstanced
	, glDrawTransformFeedbackStreamInstanced
	, glGetActiveAtomicCounterBufferiv
	, glGetInternalformativ
	, glMemoryBarrier
	, glTexStorage1D
	, glTexStorage2D
	, glTexStorage3D
	, gl_ACTIVE_ATOMIC_COUNTER_BUFFERS
	, gl_ALL_BARRIER_BITS
	, gl_ATOMIC_COUNTER_BARRIER_BIT
	, gl_ATOMIC_COUNTER_BUFFER
	, gl_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS
	, gl_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTER_INDICES
	, gl_ATOMIC_COUNTER_BUFFER_BINDING
	, gl_ATOMIC_COUNTER_BUFFER_DATA_SIZE
	, gl_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_FRAGMENT_SHADER
	, gl_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_GEOMETRY_SHADER
	, gl_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_CONTROL_SHADER
	, gl_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_EVALUATION_SHADER
	, gl_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_VERTEX_SHADER
	, gl_ATOMIC_COUNTER_BUFFER_SIZE
	, gl_ATOMIC_COUNTER_BUFFER_START
	, gl_BUFFER_UPDATE_BARRIER_BIT
	, gl_COMMAND_BARRIER_BIT
	, gl_COMPRESSED_RGBA_BPTC_UNORM
	, gl_COMPRESSED_RGB_BPTC_SIGNED_FLOAT
	, gl_COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT
	, gl_COMPRESSED_SRGB_ALPHA_BPTC_UNORM
	, gl_COPY_READ_BUFFER_BINDING
	, gl_COPY_WRITE_BUFFER_BINDING
	, gl_ELEMENT_ARRAY_BARRIER_BIT
	, gl_FRAMEBUFFER_BARRIER_BIT
	, gl_IMAGE_1D
	, gl_IMAGE_1D_ARRAY
	, gl_IMAGE_2D
	, gl_IMAGE_2D_ARRAY
	, gl_IMAGE_2D_MULTISAMPLE
	, gl_IMAGE_2D_MULTISAMPLE_ARRAY
	, gl_IMAGE_2D_RECT
	, gl_IMAGE_3D
	, gl_IMAGE_BINDING_ACCESS
	, gl_IMAGE_BINDING_FORMAT
	, gl_IMAGE_BINDING_LAYER
	, gl_IMAGE_BINDING_LAYERED
	, gl_IMAGE_BINDING_LEVEL
	, gl_IMAGE_BINDING_NAME
	, gl_IMAGE_BUFFER
	, gl_IMAGE_CUBE
	, gl_IMAGE_CUBE_MAP_ARRAY
	, gl_IMAGE_FORMAT_COMPATIBILITY_BY_CLASS
	, gl_IMAGE_FORMAT_COMPATIBILITY_BY_SIZE
	, gl_IMAGE_FORMAT_COMPATIBILITY_TYPE
	, gl_INT_IMAGE_1D
	, gl_INT_IMAGE_1D_ARRAY
	, gl_INT_IMAGE_2D
	, gl_INT_IMAGE_2D_ARRAY
	, gl_INT_IMAGE_2D_MULTISAMPLE
	, gl_INT_IMAGE_2D_MULTISAMPLE_ARRAY
	, gl_INT_IMAGE_2D_RECT
	, gl_INT_IMAGE_3D
	, gl_INT_IMAGE_BUFFER
	, gl_INT_IMAGE_CUBE
	, gl_INT_IMAGE_CUBE_MAP_ARRAY
	, gl_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS
	, gl_MAX_ATOMIC_COUNTER_BUFFER_SIZE
	, gl_MAX_COMBINED_ATOMIC_COUNTERS
	, gl_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS
	, gl_MAX_COMBINED_IMAGE_UNIFORMS
	, gl_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS
	, gl_MAX_FRAGMENT_ATOMIC_COUNTERS
	, gl_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS
	, gl_MAX_FRAGMENT_IMAGE_UNIFORMS
	, gl_MAX_GEOMETRY_ATOMIC_COUNTERS
	, gl_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS
	, gl_MAX_GEOMETRY_IMAGE_UNIFORMS
	, gl_MAX_IMAGE_SAMPLES
	, gl_MAX_IMAGE_UNITS
	, gl_MAX_TESS_CONTROL_ATOMIC_COUNTERS
	, gl_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS
	, gl_MAX_TESS_CONTROL_IMAGE_UNIFORMS
	, gl_MAX_TESS_EVALUATION_ATOMIC_COUNTERS
	, gl_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS
	, gl_MAX_TESS_EVALUATION_IMAGE_UNIFORMS
	, gl_MAX_VERTEX_ATOMIC_COUNTERS
	, gl_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS
	, gl_MAX_VERTEX_IMAGE_UNIFORMS
	, gl_MIN_MAP_BUFFER_ALIGNMENT
	, gl_NUM_SAMPLE_COUNTS
	, gl_PACK_COMPRESSED_BLOCK_DEPTH
	, gl_PACK_COMPRESSED_BLOCK_HEIGHT
	, gl_PACK_COMPRESSED_BLOCK_SIZE
	, gl_PACK_COMPRESSED_BLOCK_WIDTH
	, gl_PIXEL_BUFFER_BARRIER_BIT
	, gl_SHADER_IMAGE_ACCESS_BARRIER_BIT
	, gl_TEXTURE_FETCH_BARRIER_BIT
	, gl_TEXTURE_IMMUTABLE_FORMAT
	, gl_TEXTURE_UPDATE_BARRIER_BIT
	, gl_TRANSFORM_FEEDBACK_ACTIVE
	, gl_TRANSFORM_FEEDBACK_BARRIER_BIT
	, gl_TRANSFORM_FEEDBACK_PAUSED
	, gl_UNIFORM_ATOMIC_COUNTER_BUFFER_INDEX
	, gl_UNIFORM_BARRIER_BIT
	, gl_UNPACK_COMPRESSED_BLOCK_DEPTH
	, gl_UNPACK_COMPRESSED_BLOCK_HEIGHT
	, gl_UNPACK_COMPRESSED_BLOCK_SIZE
	, gl_UNPACK_COMPRESSED_BLOCK_WIDTH
	, gl_UNSIGNED_INT_ATOMIC_COUNTER
	, gl_UNSIGNED_INT_IMAGE_1D
	, gl_UNSIGNED_INT_IMAGE_1D_ARRAY
	, gl_UNSIGNED_INT_IMAGE_2D
	, gl_UNSIGNED_INT_IMAGE_2D_ARRAY
	, gl_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE
	, gl_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY
	, gl_UNSIGNED_INT_IMAGE_2D_RECT
	, gl_UNSIGNED_INT_IMAGE_3D
	, gl_UNSIGNED_INT_IMAGE_BUFFER
	, gl_UNSIGNED_INT_IMAGE_CUBE
	, gl_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY
	, gl_VERTEX_ATTRIB_ARRAY_BARRIER_BIT
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

import Graphics.OpenGL.Internal.Shared

import Graphics.OpenGL.Profile.Core41

gl_COMPRESSED_RGBA_BPTC_UNORM :: GLenum
gl_COMPRESSED_RGBA_BPTC_UNORM = 0x8E8C

gl_COMPRESSED_RGB_BPTC_SIGNED_FLOAT :: GLenum
gl_COMPRESSED_RGB_BPTC_SIGNED_FLOAT = 0x8E8E

gl_COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT :: GLenum
gl_COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT = 0x8E8F

gl_COMPRESSED_SRGB_ALPHA_BPTC_UNORM :: GLenum
gl_COMPRESSED_SRGB_ALPHA_BPTC_UNORM = 0x8E8D