-- This file was automatically generated.
module Graphics.OpenGL.Profile.Core41 (
	-- * Graphics.OpenGL.Profile.Core41
	  module Graphics.OpenGL.Profile.Core40
	, glActiveShaderProgram
	, glBindProgramPipeline
	, glClearDepthf
	, glCreateShaderProgramv
	, glDeleteProgramPipelines
	, glDepthRangeArrayv
	, glDepthRangeIndexed
	, glDepthRangef
	, glGenProgramPipelines
	, glGetDoublei_v
	, glGetFloati_v
	, glGetProgramBinary
	, glGetProgramPipelineInfoLog
	, glGetProgramPipelineiv
	, glGetShaderPrecisionFormat
	, glGetVertexAttribLdv
	, glIsProgramPipeline
	, glProgramBinary
	, glProgramParameteri
	, glProgramUniform1d
	, glProgramUniform1dv
	, glProgramUniform1f
	, glProgramUniform1fv
	, glProgramUniform1i
	, glProgramUniform1iv
	, glProgramUniform1ui
	, glProgramUniform1uiv
	, glProgramUniform2d
	, glProgramUniform2dv
	, glProgramUniform2f
	, glProgramUniform2fv
	, glProgramUniform2i
	, glProgramUniform2iv
	, glProgramUniform2ui
	, glProgramUniform2uiv
	, glProgramUniform3d
	, glProgramUniform3dv
	, glProgramUniform3f
	, glProgramUniform3fv
	, glProgramUniform3i
	, glProgramUniform3iv
	, glProgramUniform3ui
	, glProgramUniform3uiv
	, glProgramUniform4d
	, glProgramUniform4dv
	, glProgramUniform4f
	, glProgramUniform4fv
	, glProgramUniform4i
	, glProgramUniform4iv
	, glProgramUniform4ui
	, glProgramUniform4uiv
	, glProgramUniformMatrix2dv
	, glProgramUniformMatrix2fv
	, glProgramUniformMatrix2x3dv
	, glProgramUniformMatrix2x3fv
	, glProgramUniformMatrix2x4dv
	, glProgramUniformMatrix2x4fv
	, glProgramUniformMatrix3dv
	, glProgramUniformMatrix3fv
	, glProgramUniformMatrix3x2dv
	, glProgramUniformMatrix3x2fv
	, glProgramUniformMatrix3x4dv
	, glProgramUniformMatrix3x4fv
	, glProgramUniformMatrix4dv
	, glProgramUniformMatrix4fv
	, glProgramUniformMatrix4x2dv
	, glProgramUniformMatrix4x2fv
	, glProgramUniformMatrix4x3dv
	, glProgramUniformMatrix4x3fv
	, glReleaseShaderCompiler
	, glScissorArrayv
	, glScissorIndexed
	, glScissorIndexedv
	, glShaderBinary
	, glUseProgramStages
	, glValidateProgramPipeline
	, glVertexAttribL1d
	, glVertexAttribL1dv
	, glVertexAttribL2d
	, glVertexAttribL2dv
	, glVertexAttribL3d
	, glVertexAttribL3dv
	, glVertexAttribL4d
	, glVertexAttribL4dv
	, glVertexAttribLPointer
	, glViewportArrayv
	, glViewportIndexedf
	, glViewportIndexedfv
	, gl_ACTIVE_PROGRAM
	, gl_ALL_SHADER_BITS
	, gl_FIXED
	, gl_FRAGMENT_SHADER_BIT
	, gl_GEOMETRY_SHADER_BIT
	, gl_HIGH_FLOAT
	, gl_HIGH_INT
	, gl_IMPLEMENTATION_COLOR_READ_FORMAT
	, gl_IMPLEMENTATION_COLOR_READ_TYPE
	, gl_LAYER_PROVOKING_VERTEX
	, gl_LOW_FLOAT
	, gl_LOW_INT
	, gl_MAX_FRAGMENT_UNIFORM_VECTORS
	, gl_MAX_VARYING_VECTORS
	, gl_MAX_VERTEX_UNIFORM_VECTORS
	, gl_MAX_VIEWPORTS
	, gl_MEDIUM_FLOAT
	, gl_MEDIUM_INT
	, gl_NUM_PROGRAM_BINARY_FORMATS
	, gl_NUM_SHADER_BINARY_FORMATS
	, gl_PROGRAM_BINARY_FORMATS
	, gl_PROGRAM_BINARY_LENGTH
	, gl_PROGRAM_BINARY_RETRIEVABLE_HINT
	, gl_PROGRAM_PIPELINE_BINDING
	, gl_PROGRAM_SEPARABLE
	, gl_RGB565
	, gl_SHADER_BINARY_FORMATS
	, gl_SHADER_COMPILER
	, gl_TESS_CONTROL_SHADER_BIT
	, gl_TESS_EVALUATION_SHADER_BIT
	, gl_UNDEFINED_VERTEX
	, gl_VERTEX_SHADER_BIT
	, gl_VIEWPORT_BOUNDS_RANGE
	, gl_VIEWPORT_INDEX_PROVOKING_VERTEX
	, gl_VIEWPORT_SUBPIXEL_BITS
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

import Graphics.OpenGL.Internal.Shared

import Graphics.OpenGL.Profile.Core40