-- This file was automatically generated.
module Graphics.OpenGL.Profile.Standard20 (
	-- * Graphics.OpenGL.Profile.Standard20
	  module Graphics.OpenGL.Profile.Standard15
	, glAttachShader
	, glBindAttribLocation
	, glBlendEquationSeparate
	, glCompileShader
	, glCreateProgram
	, glCreateShader
	, glDeleteProgram
	, glDeleteShader
	, glDetachShader
	, glDisableVertexAttribArray
	, glDrawBuffers
	, glEnableVertexAttribArray
	, glGetActiveAttrib
	, glGetActiveUniform
	, glGetAttachedShaders
	, glGetAttribLocation
	, glGetProgramInfoLog
	, glGetProgramiv
	, glGetShaderInfoLog
	, glGetShaderSource
	, glGetShaderiv
	, glGetUniformLocation
	, glGetUniformfv
	, glGetUniformiv
	, glGetVertexAttribPointerv
	, glGetVertexAttribdv
	, glGetVertexAttribfv
	, glGetVertexAttribiv
	, glIsProgram
	, glIsShader
	, glLinkProgram
	, glShaderSource
	, glStencilFuncSeparate
	, glStencilMaskSeparate
	, glStencilOpSeparate
	, glUniform1f
	, glUniform1fv
	, glUniform1i
	, glUniform1iv
	, glUniform2f
	, glUniform2fv
	, glUniform2i
	, glUniform2iv
	, glUniform3f
	, glUniform3fv
	, glUniform3i
	, glUniform3iv
	, glUniform4f
	, glUniform4fv
	, glUniform4i
	, glUniform4iv
	, glUniformMatrix2fv
	, glUniformMatrix3fv
	, glUniformMatrix4fv
	, glUseProgram
	, glValidateProgram
	, glVertexAttrib1d
	, glVertexAttrib1dv
	, glVertexAttrib1f
	, glVertexAttrib1fv
	, glVertexAttrib1s
	, glVertexAttrib1sv
	, glVertexAttrib2d
	, glVertexAttrib2dv
	, glVertexAttrib2f
	, glVertexAttrib2fv
	, glVertexAttrib2s
	, glVertexAttrib2sv
	, glVertexAttrib3d
	, glVertexAttrib3dv
	, glVertexAttrib3f
	, glVertexAttrib3fv
	, glVertexAttrib3s
	, glVertexAttrib3sv
	, glVertexAttrib4Nbv
	, glVertexAttrib4Niv
	, glVertexAttrib4Nsv
	, glVertexAttrib4Nub
	, glVertexAttrib4Nubv
	, glVertexAttrib4Nuiv
	, glVertexAttrib4Nusv
	, glVertexAttrib4bv
	, glVertexAttrib4d
	, glVertexAttrib4dv
	, glVertexAttrib4f
	, glVertexAttrib4fv
	, glVertexAttrib4iv
	, glVertexAttrib4s
	, glVertexAttrib4sv
	, glVertexAttrib4ubv
	, glVertexAttrib4uiv
	, glVertexAttrib4usv
	, glVertexAttribPointer
	, gl_ACTIVE_ATTRIBUTES
	, gl_ACTIVE_ATTRIBUTE_MAX_LENGTH
	, gl_ACTIVE_UNIFORMS
	, gl_ACTIVE_UNIFORM_MAX_LENGTH
	, gl_ATTACHED_SHADERS
	, gl_BLEND_EQUATION_ALPHA
	, gl_BLEND_EQUATION_RGB
	, gl_BOOL
	, gl_BOOL_VEC2
	, gl_BOOL_VEC3
	, gl_BOOL_VEC4
	, gl_COMPILE_STATUS
	, gl_COORD_REPLACE
	, gl_CURRENT_PROGRAM
	, gl_CURRENT_VERTEX_ATTRIB
	, gl_DELETE_STATUS
	, gl_DRAW_BUFFER0
	, gl_DRAW_BUFFER1
	, gl_DRAW_BUFFER10
	, gl_DRAW_BUFFER11
	, gl_DRAW_BUFFER12
	, gl_DRAW_BUFFER13
	, gl_DRAW_BUFFER14
	, gl_DRAW_BUFFER15
	, gl_DRAW_BUFFER2
	, gl_DRAW_BUFFER3
	, gl_DRAW_BUFFER4
	, gl_DRAW_BUFFER5
	, gl_DRAW_BUFFER6
	, gl_DRAW_BUFFER7
	, gl_DRAW_BUFFER8
	, gl_DRAW_BUFFER9
	, gl_FLOAT_MAT2
	, gl_FLOAT_MAT3
	, gl_FLOAT_MAT4
	, gl_FLOAT_VEC2
	, gl_FLOAT_VEC3
	, gl_FLOAT_VEC4
	, gl_FRAGMENT_SHADER
	, gl_FRAGMENT_SHADER_DERIVATIVE_HINT
	, gl_INFO_LOG_LENGTH
	, gl_INT_VEC2
	, gl_INT_VEC3
	, gl_INT_VEC4
	, gl_LINK_STATUS
	, gl_LOWER_LEFT
	, gl_MAX_COMBINED_TEXTURE_IMAGE_UNITS
	, gl_MAX_DRAW_BUFFERS
	, gl_MAX_FRAGMENT_UNIFORM_COMPONENTS
	, gl_MAX_TEXTURE_COORDS
	, gl_MAX_TEXTURE_IMAGE_UNITS
	, gl_MAX_VARYING_FLOATS
	, gl_MAX_VERTEX_ATTRIBS
	, gl_MAX_VERTEX_TEXTURE_IMAGE_UNITS
	, gl_MAX_VERTEX_UNIFORM_COMPONENTS
	, gl_POINT_SPRITE
	, gl_POINT_SPRITE_COORD_ORIGIN
	, gl_SAMPLER_1D
	, gl_SAMPLER_1D_SHADOW
	, gl_SAMPLER_2D
	, gl_SAMPLER_2D_SHADOW
	, gl_SAMPLER_3D
	, gl_SAMPLER_CUBE
	, gl_SHADER_SOURCE_LENGTH
	, gl_SHADER_TYPE
	, gl_SHADING_LANGUAGE_VERSION
	, gl_STENCIL_BACK_FAIL
	, gl_STENCIL_BACK_FUNC
	, gl_STENCIL_BACK_PASS_DEPTH_FAIL
	, gl_STENCIL_BACK_PASS_DEPTH_PASS
	, gl_STENCIL_BACK_REF
	, gl_STENCIL_BACK_VALUE_MASK
	, gl_STENCIL_BACK_WRITEMASK
	, gl_UPPER_LEFT
	, gl_VALIDATE_STATUS
	, gl_VERTEX_ATTRIB_ARRAY_ENABLED
	, gl_VERTEX_ATTRIB_ARRAY_NORMALIZED
	, gl_VERTEX_ATTRIB_ARRAY_POINTER
	, gl_VERTEX_ATTRIB_ARRAY_SIZE
	, gl_VERTEX_ATTRIB_ARRAY_STRIDE
	, gl_VERTEX_ATTRIB_ARRAY_TYPE
	, gl_VERTEX_PROGRAM_POINT_SIZE
	, gl_VERTEX_PROGRAM_TWO_SIDE
	, gl_VERTEX_SHADER
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

import Graphics.OpenGL.Internal.Shared

import Graphics.OpenGL.Profile.Standard15