-- This file was automatically generated.
module Graphics.OpenGL.Profile.Standard13 (
	-- * Graphics.OpenGL.Profile.Standard13
	  module Graphics.OpenGL.Profile.Standard12
	, glActiveTexture
	, glClientActiveTexture
	, glCompressedTexImage1D
	, glCompressedTexImage2D
	, glCompressedTexImage3D
	, glCompressedTexSubImage1D
	, glCompressedTexSubImage2D
	, glCompressedTexSubImage3D
	, glGetCompressedTexImage
	, glLoadTransposeMatrixd
	, glLoadTransposeMatrixf
	, glMultTransposeMatrixd
	, glMultTransposeMatrixf
	, glMultiTexCoord1d
	, glMultiTexCoord1dv
	, glMultiTexCoord1f
	, glMultiTexCoord1fv
	, glMultiTexCoord1i
	, glMultiTexCoord1iv
	, glMultiTexCoord1s
	, glMultiTexCoord1sv
	, glMultiTexCoord2d
	, glMultiTexCoord2dv
	, glMultiTexCoord2f
	, glMultiTexCoord2fv
	, glMultiTexCoord2i
	, glMultiTexCoord2iv
	, glMultiTexCoord2s
	, glMultiTexCoord2sv
	, glMultiTexCoord3d
	, glMultiTexCoord3dv
	, glMultiTexCoord3f
	, glMultiTexCoord3fv
	, glMultiTexCoord3i
	, glMultiTexCoord3iv
	, glMultiTexCoord3s
	, glMultiTexCoord3sv
	, glMultiTexCoord4d
	, glMultiTexCoord4dv
	, glMultiTexCoord4f
	, glMultiTexCoord4fv
	, glMultiTexCoord4i
	, glMultiTexCoord4iv
	, glMultiTexCoord4s
	, glMultiTexCoord4sv
	, glSampleCoverage
	, gl_ACTIVE_TEXTURE
	, gl_ADD_SIGNED
	, gl_CLAMP_TO_BORDER
	, gl_CLIENT_ACTIVE_TEXTURE
	, gl_COMBINE
	, gl_COMBINE_ALPHA
	, gl_COMBINE_RGB
	, gl_COMPRESSED_ALPHA
	, gl_COMPRESSED_INTENSITY
	, gl_COMPRESSED_LUMINANCE
	, gl_COMPRESSED_LUMINANCE_ALPHA
	, gl_COMPRESSED_RGB
	, gl_COMPRESSED_RGBA
	, gl_COMPRESSED_TEXTURE_FORMATS
	, gl_CONSTANT
	, gl_DOT3_RGB
	, gl_DOT3_RGBA
	, gl_INTERPOLATE
	, gl_MAX_CUBE_MAP_TEXTURE_SIZE
	, gl_MAX_TEXTURE_UNITS
	, gl_MULTISAMPLE
	, gl_MULTISAMPLE_BIT
	, gl_NORMAL_MAP
	, gl_NUM_COMPRESSED_TEXTURE_FORMATS
	, gl_OPERAND0_ALPHA
	, gl_OPERAND0_RGB
	, gl_OPERAND1_ALPHA
	, gl_OPERAND1_RGB
	, gl_OPERAND2_ALPHA
	, gl_OPERAND2_RGB
	, gl_PREVIOUS
	, gl_PRIMARY_COLOR
	, gl_PROXY_TEXTURE_CUBE_MAP
	, gl_REFLECTION_MAP
	, gl_RGB_SCALE
	, gl_SAMPLES
	, gl_SAMPLE_ALPHA_TO_COVERAGE
	, gl_SAMPLE_ALPHA_TO_ONE
	, gl_SAMPLE_BUFFERS
	, gl_SAMPLE_COVERAGE
	, gl_SAMPLE_COVERAGE_INVERT
	, gl_SAMPLE_COVERAGE_VALUE
	, gl_SOURCE0_ALPHA
	, gl_SOURCE0_RGB
	, gl_SOURCE1_ALPHA
	, gl_SOURCE1_RGB
	, gl_SOURCE2_ALPHA
	, gl_SOURCE2_RGB
	, gl_SUBTRACT
	, gl_TEXTURE0
	, gl_TEXTURE1
	, gl_TEXTURE10
	, gl_TEXTURE11
	, gl_TEXTURE12
	, gl_TEXTURE13
	, gl_TEXTURE14
	, gl_TEXTURE15
	, gl_TEXTURE16
	, gl_TEXTURE17
	, gl_TEXTURE18
	, gl_TEXTURE19
	, gl_TEXTURE2
	, gl_TEXTURE20
	, gl_TEXTURE21
	, gl_TEXTURE22
	, gl_TEXTURE23
	, gl_TEXTURE24
	, gl_TEXTURE25
	, gl_TEXTURE26
	, gl_TEXTURE27
	, gl_TEXTURE28
	, gl_TEXTURE29
	, gl_TEXTURE3
	, gl_TEXTURE30
	, gl_TEXTURE31
	, gl_TEXTURE4
	, gl_TEXTURE5
	, gl_TEXTURE6
	, gl_TEXTURE7
	, gl_TEXTURE8
	, gl_TEXTURE9
	, gl_TEXTURE_BINDING_CUBE_MAP
	, gl_TEXTURE_COMPRESSED
	, gl_TEXTURE_COMPRESSED_IMAGE_SIZE
	, gl_TEXTURE_COMPRESSION_HINT
	, gl_TEXTURE_CUBE_MAP
	, gl_TEXTURE_CUBE_MAP_NEGATIVE_X
	, gl_TEXTURE_CUBE_MAP_NEGATIVE_Y
	, gl_TEXTURE_CUBE_MAP_NEGATIVE_Z
	, gl_TEXTURE_CUBE_MAP_POSITIVE_X
	, gl_TEXTURE_CUBE_MAP_POSITIVE_Y
	, gl_TEXTURE_CUBE_MAP_POSITIVE_Z
	, gl_TRANSPOSE_COLOR_MATRIX
	, gl_TRANSPOSE_MODELVIEW_MATRIX
	, gl_TRANSPOSE_PROJECTION_MATRIX
	, gl_TRANSPOSE_TEXTURE_MATRIX
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

import Graphics.OpenGL.Internal.Shared

import Graphics.OpenGL.Profile.Standard12