-- This file was automatically generated.
module Graphics.OpenGL.Extension.SGIS.TextureSelect (
	-- * Extension Support
	  gl_SGIS_texture_select

	-- * GL_SGIS_texture_select
	, gl_DUAL_ALPHA12_SGIS
	, gl_DUAL_ALPHA16_SGIS
	, gl_DUAL_ALPHA4_SGIS
	, gl_DUAL_ALPHA8_SGIS
	, gl_DUAL_INTENSITY12_SGIS
	, gl_DUAL_INTENSITY16_SGIS
	, gl_DUAL_INTENSITY4_SGIS
	, gl_DUAL_INTENSITY8_SGIS
	, gl_DUAL_LUMINANCE12_SGIS
	, gl_DUAL_LUMINANCE16_SGIS
	, gl_DUAL_LUMINANCE4_SGIS
	, gl_DUAL_LUMINANCE8_SGIS
	, gl_DUAL_LUMINANCE_ALPHA4_SGIS
	, gl_DUAL_LUMINANCE_ALPHA8_SGIS
	, gl_DUAL_TEXTURE_SELECT_SGIS
	, gl_QUAD_ALPHA4_SGIS
	, gl_QUAD_ALPHA8_SGIS
	, gl_QUAD_INTENSITY4_SGIS
	, gl_QUAD_INTENSITY8_SGIS
	, gl_QUAD_LUMINANCE4_SGIS
	, gl_QUAD_LUMINANCE8_SGIS
	, gl_QUAD_TEXTURE_SELECT_SGIS
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

gl_SGIS_texture_select :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_SGIS_texture_select = extGL 627

gl_DUAL_ALPHA12_SGIS :: GLenum
gl_DUAL_ALPHA12_SGIS = 0x8112

gl_DUAL_ALPHA16_SGIS :: GLenum
gl_DUAL_ALPHA16_SGIS = 0x8113

gl_DUAL_ALPHA4_SGIS :: GLenum
gl_DUAL_ALPHA4_SGIS = 0x8110

gl_DUAL_ALPHA8_SGIS :: GLenum
gl_DUAL_ALPHA8_SGIS = 0x8111

gl_DUAL_INTENSITY12_SGIS :: GLenum
gl_DUAL_INTENSITY12_SGIS = 0x811A

gl_DUAL_INTENSITY16_SGIS :: GLenum
gl_DUAL_INTENSITY16_SGIS = 0x811B

gl_DUAL_INTENSITY4_SGIS :: GLenum
gl_DUAL_INTENSITY4_SGIS = 0x8118

gl_DUAL_INTENSITY8_SGIS :: GLenum
gl_DUAL_INTENSITY8_SGIS = 0x8119

gl_DUAL_LUMINANCE12_SGIS :: GLenum
gl_DUAL_LUMINANCE12_SGIS = 0x8116

gl_DUAL_LUMINANCE16_SGIS :: GLenum
gl_DUAL_LUMINANCE16_SGIS = 0x8117

gl_DUAL_LUMINANCE4_SGIS :: GLenum
gl_DUAL_LUMINANCE4_SGIS = 0x8114

gl_DUAL_LUMINANCE8_SGIS :: GLenum
gl_DUAL_LUMINANCE8_SGIS = 0x8115

gl_DUAL_LUMINANCE_ALPHA4_SGIS :: GLenum
gl_DUAL_LUMINANCE_ALPHA4_SGIS = 0x811C

gl_DUAL_LUMINANCE_ALPHA8_SGIS :: GLenum
gl_DUAL_LUMINANCE_ALPHA8_SGIS = 0x811D

gl_DUAL_TEXTURE_SELECT_SGIS :: GLenum
gl_DUAL_TEXTURE_SELECT_SGIS = 0x8124

gl_QUAD_ALPHA4_SGIS :: GLenum
gl_QUAD_ALPHA4_SGIS = 0x811E

gl_QUAD_ALPHA8_SGIS :: GLenum
gl_QUAD_ALPHA8_SGIS = 0x811F

gl_QUAD_INTENSITY4_SGIS :: GLenum
gl_QUAD_INTENSITY4_SGIS = 0x8122

gl_QUAD_INTENSITY8_SGIS :: GLenum
gl_QUAD_INTENSITY8_SGIS = 0x8123

gl_QUAD_LUMINANCE4_SGIS :: GLenum
gl_QUAD_LUMINANCE4_SGIS = 0x8120

gl_QUAD_LUMINANCE8_SGIS :: GLenum
gl_QUAD_LUMINANCE8_SGIS = 0x8121

gl_QUAD_TEXTURE_SELECT_SGIS :: GLenum
gl_QUAD_TEXTURE_SELECT_SGIS = 0x8125