-- This file was automatically generated.
module Graphics.OpenGL.Extension.APPLE.FloatPixels (
	-- * Extension Support
	  gl_APPLE_float_pixels

	-- * GL_APPLE_float_pixels
	, gl_ALPHA_FLOAT16_APPLE
	, gl_ALPHA_FLOAT32_APPLE
	, gl_COLOR_FLOAT_APPLE
	, gl_HALF_APPLE
	, gl_INTENSITY_FLOAT16_APPLE
	, gl_INTENSITY_FLOAT32_APPLE
	, gl_LUMINANCE_ALPHA_FLOAT16_APPLE
	, gl_LUMINANCE_ALPHA_FLOAT32_APPLE
	, gl_LUMINANCE_FLOAT16_APPLE
	, gl_LUMINANCE_FLOAT32_APPLE
	, gl_RGBA_FLOAT16_APPLE
	, gl_RGBA_FLOAT32_APPLE
	, gl_RGB_FLOAT16_APPLE
	, gl_RGB_FLOAT32_APPLE
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

gl_APPLE_float_pixels :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_APPLE_float_pixels = extGL 51

gl_ALPHA_FLOAT16_APPLE :: GLenum
gl_ALPHA_FLOAT16_APPLE = 0x881C

gl_ALPHA_FLOAT32_APPLE :: GLenum
gl_ALPHA_FLOAT32_APPLE = 0x8816

gl_COLOR_FLOAT_APPLE :: GLenum
gl_COLOR_FLOAT_APPLE = 0x8A0F

gl_HALF_APPLE :: GLenum
gl_HALF_APPLE = 0x140B

gl_INTENSITY_FLOAT16_APPLE :: GLenum
gl_INTENSITY_FLOAT16_APPLE = 0x881D

gl_INTENSITY_FLOAT32_APPLE :: GLenum
gl_INTENSITY_FLOAT32_APPLE = 0x8817

gl_LUMINANCE_ALPHA_FLOAT16_APPLE :: GLenum
gl_LUMINANCE_ALPHA_FLOAT16_APPLE = 0x881F

gl_LUMINANCE_ALPHA_FLOAT32_APPLE :: GLenum
gl_LUMINANCE_ALPHA_FLOAT32_APPLE = 0x8819

gl_LUMINANCE_FLOAT16_APPLE :: GLenum
gl_LUMINANCE_FLOAT16_APPLE = 0x881E

gl_LUMINANCE_FLOAT32_APPLE :: GLenum
gl_LUMINANCE_FLOAT32_APPLE = 0x8818

gl_RGBA_FLOAT16_APPLE :: GLenum
gl_RGBA_FLOAT16_APPLE = 0x881A

gl_RGBA_FLOAT32_APPLE :: GLenum
gl_RGBA_FLOAT32_APPLE = 0x8814

gl_RGB_FLOAT16_APPLE :: GLenum
gl_RGB_FLOAT16_APPLE = 0x881B

gl_RGB_FLOAT32_APPLE :: GLenum
gl_RGB_FLOAT32_APPLE = 0x8815