-- This file was automatically generated.
module Graphics.OpenGL.Extension.NVX.GpuMemoryInfo (
	-- * Extension Support
	  gl_NVX_gpu_memory_info

	-- * GL_NVX_gpu_memory_info
	, gl_GPU_MEMORY_INFO_CURRENT_AVAILABLE_VIDMEM_NVX
	, gl_GPU_MEMORY_INFO_DEDICATED_VIDMEM_NVX
	, gl_GPU_MEMORY_INFO_EVICTED_MEMORY_NVX
	, gl_GPU_MEMORY_INFO_EVICTION_COUNT_NVX
	, gl_GPU_MEMORY_INFO_TOTAL_AVAILABLE_MEMORY_NVX
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

gl_NVX_gpu_memory_info :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_NVX_gpu_memory_info = extGL 427

gl_GPU_MEMORY_INFO_CURRENT_AVAILABLE_VIDMEM_NVX :: GLenum
gl_GPU_MEMORY_INFO_CURRENT_AVAILABLE_VIDMEM_NVX = 0x9049

gl_GPU_MEMORY_INFO_DEDICATED_VIDMEM_NVX :: GLenum
gl_GPU_MEMORY_INFO_DEDICATED_VIDMEM_NVX = 0x9047

gl_GPU_MEMORY_INFO_EVICTED_MEMORY_NVX :: GLenum
gl_GPU_MEMORY_INFO_EVICTED_MEMORY_NVX = 0x904B

gl_GPU_MEMORY_INFO_EVICTION_COUNT_NVX :: GLenum
gl_GPU_MEMORY_INFO_EVICTION_COUNT_NVX = 0x904A

gl_GPU_MEMORY_INFO_TOTAL_AVAILABLE_MEMORY_NVX :: GLenum
gl_GPU_MEMORY_INFO_TOTAL_AVAILABLE_MEMORY_NVX = 0x9048