-- This file was automatically generated.
module Graphics.OpenGL.Extension.ARB.TextureFloat (
	-- * Extension Support
	  gl_ARB_texture_float

	-- * GL_ARB_texture_float
	, gl_ALPHA16F_ARB
	, gl_ALPHA32F_ARB
	, gl_INTENSITY16F_ARB
	, gl_INTENSITY32F_ARB
	, gl_LUMINANCE16F_ARB
	, gl_LUMINANCE32F_ARB
	, gl_LUMINANCE_ALPHA16F_ARB
	, gl_LUMINANCE_ALPHA32F_ARB
	, gl_RGB16F_ARB
	, gl_RGB32F_ARB
	, gl_RGBA16F_ARB
	, gl_RGBA32F_ARB
	, gl_TEXTURE_ALPHA_TYPE_ARB
	, gl_TEXTURE_BLUE_TYPE_ARB
	, gl_TEXTURE_DEPTH_TYPE_ARB
	, gl_TEXTURE_GREEN_TYPE_ARB
	, gl_TEXTURE_INTENSITY_TYPE_ARB
	, gl_TEXTURE_LUMINANCE_TYPE_ARB
	, gl_TEXTURE_RED_TYPE_ARB
	, gl_UNSIGNED_NORMALIZED_ARB
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

gl_ARB_texture_float :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_ARB_texture_float = extGL 188

gl_ALPHA16F_ARB :: GLenum
gl_ALPHA16F_ARB = 0x881C

gl_ALPHA32F_ARB :: GLenum
gl_ALPHA32F_ARB = 0x8816

gl_INTENSITY16F_ARB :: GLenum
gl_INTENSITY16F_ARB = 0x881D

gl_INTENSITY32F_ARB :: GLenum
gl_INTENSITY32F_ARB = 0x8817

gl_LUMINANCE16F_ARB :: GLenum
gl_LUMINANCE16F_ARB = 0x881E

gl_LUMINANCE32F_ARB :: GLenum
gl_LUMINANCE32F_ARB = 0x8818

gl_LUMINANCE_ALPHA16F_ARB :: GLenum
gl_LUMINANCE_ALPHA16F_ARB = 0x881F

gl_LUMINANCE_ALPHA32F_ARB :: GLenum
gl_LUMINANCE_ALPHA32F_ARB = 0x8819

gl_RGB16F_ARB :: GLenum
gl_RGB16F_ARB = 0x881B

gl_RGB32F_ARB :: GLenum
gl_RGB32F_ARB = 0x8815

gl_RGBA16F_ARB :: GLenum
gl_RGBA16F_ARB = 0x881A

gl_RGBA32F_ARB :: GLenum
gl_RGBA32F_ARB = 0x8814

gl_TEXTURE_ALPHA_TYPE_ARB :: GLenum
gl_TEXTURE_ALPHA_TYPE_ARB = 0x8C13

gl_TEXTURE_BLUE_TYPE_ARB :: GLenum
gl_TEXTURE_BLUE_TYPE_ARB = 0x8C12

gl_TEXTURE_DEPTH_TYPE_ARB :: GLenum
gl_TEXTURE_DEPTH_TYPE_ARB = 0x8C16

gl_TEXTURE_GREEN_TYPE_ARB :: GLenum
gl_TEXTURE_GREEN_TYPE_ARB = 0x8C11

gl_TEXTURE_INTENSITY_TYPE_ARB :: GLenum
gl_TEXTURE_INTENSITY_TYPE_ARB = 0x8C15

gl_TEXTURE_LUMINANCE_TYPE_ARB :: GLenum
gl_TEXTURE_LUMINANCE_TYPE_ARB = 0x8C14

gl_TEXTURE_RED_TYPE_ARB :: GLenum
gl_TEXTURE_RED_TYPE_ARB = 0x8C10

gl_UNSIGNED_NORMALIZED_ARB :: GLenum
gl_UNSIGNED_NORMALIZED_ARB = 0x8C17