-- This file was automatically generated.
module Graphics.OpenGL.Extension.NV.TextureShader (
	-- * Extension Support
	  gl_NV_texture_shader

	-- * GL_NV_texture_shader
	, gl_CONST_EYE_NV
	, gl_CULL_FRAGMENT_NV
	, gl_CULL_MODES_NV
	, gl_DEPENDENT_AR_TEXTURE_2D_NV
	, gl_DEPENDENT_GB_TEXTURE_2D_NV
	, gl_DOT_PRODUCT_CONST_EYE_REFLECT_CUBE_MAP_NV
	, gl_DOT_PRODUCT_DEPTH_REPLACE_NV
	, gl_DOT_PRODUCT_DIFFUSE_CUBE_MAP_NV
	, gl_DOT_PRODUCT_NV
	, gl_DOT_PRODUCT_REFLECT_CUBE_MAP_NV
	, gl_DOT_PRODUCT_TEXTURE_2D_NV
	, gl_DOT_PRODUCT_TEXTURE_CUBE_MAP_NV
	, gl_DOT_PRODUCT_TEXTURE_RECTANGLE_NV
	, gl_DSDT8_MAG8_INTENSITY8_NV
	, gl_DSDT8_MAG8_NV
	, gl_DSDT8_NV
	, gl_DSDT_MAG_INTENSITY_NV
	, gl_DSDT_MAG_NV
	, gl_DSDT_MAG_VIB_NV
	, gl_DSDT_NV
	, gl_DS_BIAS_NV
	, gl_DS_SCALE_NV
	, gl_DT_BIAS_NV
	, gl_DT_SCALE_NV
	, gl_HILO16_NV
	, gl_HILO_NV
	, gl_HI_BIAS_NV
	, gl_HI_SCALE_NV
	, gl_LO_BIAS_NV
	, gl_LO_SCALE_NV
	, gl_MAGNITUDE_BIAS_NV
	, gl_MAGNITUDE_SCALE_NV
	, gl_OFFSET_TEXTURE_2D_BIAS_NV
	, gl_OFFSET_TEXTURE_2D_MATRIX_NV
	, gl_OFFSET_TEXTURE_2D_NV
	, gl_OFFSET_TEXTURE_2D_SCALE_NV
	, gl_OFFSET_TEXTURE_BIAS_NV
	, gl_OFFSET_TEXTURE_MATRIX_NV
	, gl_OFFSET_TEXTURE_RECTANGLE_NV
	, gl_OFFSET_TEXTURE_RECTANGLE_SCALE_NV
	, gl_OFFSET_TEXTURE_SCALE_NV
	, gl_PASS_THROUGH_NV
	, gl_PREVIOUS_TEXTURE_INPUT_NV
	, gl_RGBA_UNSIGNED_DOT_PRODUCT_MAPPING_NV
	, gl_SHADER_CONSISTENT_NV
	, gl_SHADER_OPERATION_NV
	, gl_SIGNED_ALPHA8_NV
	, gl_SIGNED_ALPHA_NV
	, gl_SIGNED_HILO16_NV
	, gl_SIGNED_HILO_NV
	, gl_SIGNED_INTENSITY8_NV
	, gl_SIGNED_INTENSITY_NV
	, gl_SIGNED_LUMINANCE8_ALPHA8_NV
	, gl_SIGNED_LUMINANCE8_NV
	, gl_SIGNED_LUMINANCE_ALPHA_NV
	, gl_SIGNED_LUMINANCE_NV
	, gl_SIGNED_RGB8_NV
	, gl_SIGNED_RGB8_UNSIGNED_ALPHA8_NV
	, gl_SIGNED_RGBA8_NV
	, gl_SIGNED_RGBA_NV
	, gl_SIGNED_RGB_NV
	, gl_SIGNED_RGB_UNSIGNED_ALPHA_NV
	, gl_TEXTURE_BORDER_VALUES_NV
	, gl_TEXTURE_DS_SIZE_NV
	, gl_TEXTURE_DT_SIZE_NV
	, gl_TEXTURE_HI_SIZE_NV
	, gl_TEXTURE_LO_SIZE_NV
	, gl_TEXTURE_MAG_SIZE_NV
	, gl_TEXTURE_SHADER_NV
	, gl_UNSIGNED_INT_8_8_S8_S8_REV_NV
	, gl_UNSIGNED_INT_S8_S8_8_8_NV
	, gl_VIBRANCE_BIAS_NV
	, gl_VIBRANCE_SCALE_NV
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

gl_NV_texture_shader :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_NV_texture_shader = extGL 524

gl_CONST_EYE_NV :: GLenum
gl_CONST_EYE_NV = 0x86E5

gl_CULL_FRAGMENT_NV :: GLenum
gl_CULL_FRAGMENT_NV = 0x86E7

gl_CULL_MODES_NV :: GLenum
gl_CULL_MODES_NV = 0x86E0

gl_DEPENDENT_AR_TEXTURE_2D_NV :: GLenum
gl_DEPENDENT_AR_TEXTURE_2D_NV = 0x86E9

gl_DEPENDENT_GB_TEXTURE_2D_NV :: GLenum
gl_DEPENDENT_GB_TEXTURE_2D_NV = 0x86EA

gl_DOT_PRODUCT_CONST_EYE_REFLECT_CUBE_MAP_NV :: GLenum
gl_DOT_PRODUCT_CONST_EYE_REFLECT_CUBE_MAP_NV = 0x86F3

gl_DOT_PRODUCT_DEPTH_REPLACE_NV :: GLenum
gl_DOT_PRODUCT_DEPTH_REPLACE_NV = 0x86ED

gl_DOT_PRODUCT_DIFFUSE_CUBE_MAP_NV :: GLenum
gl_DOT_PRODUCT_DIFFUSE_CUBE_MAP_NV = 0x86F1

gl_DOT_PRODUCT_NV :: GLenum
gl_DOT_PRODUCT_NV = 0x86EC

gl_DOT_PRODUCT_REFLECT_CUBE_MAP_NV :: GLenum
gl_DOT_PRODUCT_REFLECT_CUBE_MAP_NV = 0x86F2

gl_DOT_PRODUCT_TEXTURE_2D_NV :: GLenum
gl_DOT_PRODUCT_TEXTURE_2D_NV = 0x86EE

gl_DOT_PRODUCT_TEXTURE_CUBE_MAP_NV :: GLenum
gl_DOT_PRODUCT_TEXTURE_CUBE_MAP_NV = 0x86F0

gl_DOT_PRODUCT_TEXTURE_RECTANGLE_NV :: GLenum
gl_DOT_PRODUCT_TEXTURE_RECTANGLE_NV = 0x864E

gl_DSDT8_MAG8_INTENSITY8_NV :: GLenum
gl_DSDT8_MAG8_INTENSITY8_NV = 0x870B

gl_DSDT8_MAG8_NV :: GLenum
gl_DSDT8_MAG8_NV = 0x870A

gl_DSDT8_NV :: GLenum
gl_DSDT8_NV = 0x8709

gl_DSDT_MAG_INTENSITY_NV :: GLenum
gl_DSDT_MAG_INTENSITY_NV = 0x86DC

gl_DSDT_MAG_NV :: GLenum
gl_DSDT_MAG_NV = 0x86F6

gl_DSDT_MAG_VIB_NV :: GLenum
gl_DSDT_MAG_VIB_NV = 0x86F7

gl_DSDT_NV :: GLenum
gl_DSDT_NV = 0x86F5

gl_DS_BIAS_NV :: GLenum
gl_DS_BIAS_NV = 0x8716

gl_DS_SCALE_NV :: GLenum
gl_DS_SCALE_NV = 0x8710

gl_DT_BIAS_NV :: GLenum
gl_DT_BIAS_NV = 0x8717

gl_DT_SCALE_NV :: GLenum
gl_DT_SCALE_NV = 0x8711

gl_HILO16_NV :: GLenum
gl_HILO16_NV = 0x86F8

gl_HILO_NV :: GLenum
gl_HILO_NV = 0x86F4

gl_HI_BIAS_NV :: GLenum
gl_HI_BIAS_NV = 0x8714

gl_HI_SCALE_NV :: GLenum
gl_HI_SCALE_NV = 0x870E

gl_LO_BIAS_NV :: GLenum
gl_LO_BIAS_NV = 0x8715

gl_LO_SCALE_NV :: GLenum
gl_LO_SCALE_NV = 0x870F

gl_MAGNITUDE_BIAS_NV :: GLenum
gl_MAGNITUDE_BIAS_NV = 0x8718

gl_MAGNITUDE_SCALE_NV :: GLenum
gl_MAGNITUDE_SCALE_NV = 0x8712

gl_OFFSET_TEXTURE_2D_BIAS_NV :: GLenum
gl_OFFSET_TEXTURE_2D_BIAS_NV = 0x86E3

gl_OFFSET_TEXTURE_2D_MATRIX_NV :: GLenum
gl_OFFSET_TEXTURE_2D_MATRIX_NV = 0x86E1

gl_OFFSET_TEXTURE_2D_NV :: GLenum
gl_OFFSET_TEXTURE_2D_NV = 0x86E8

gl_OFFSET_TEXTURE_2D_SCALE_NV :: GLenum
gl_OFFSET_TEXTURE_2D_SCALE_NV = 0x86E2

gl_OFFSET_TEXTURE_BIAS_NV :: GLenum
gl_OFFSET_TEXTURE_BIAS_NV = 0x86E3

gl_OFFSET_TEXTURE_MATRIX_NV :: GLenum
gl_OFFSET_TEXTURE_MATRIX_NV = 0x86E1

gl_OFFSET_TEXTURE_RECTANGLE_NV :: GLenum
gl_OFFSET_TEXTURE_RECTANGLE_NV = 0x864C

gl_OFFSET_TEXTURE_RECTANGLE_SCALE_NV :: GLenum
gl_OFFSET_TEXTURE_RECTANGLE_SCALE_NV = 0x864D

gl_OFFSET_TEXTURE_SCALE_NV :: GLenum
gl_OFFSET_TEXTURE_SCALE_NV = 0x86E2

gl_PASS_THROUGH_NV :: GLenum
gl_PASS_THROUGH_NV = 0x86E6

gl_PREVIOUS_TEXTURE_INPUT_NV :: GLenum
gl_PREVIOUS_TEXTURE_INPUT_NV = 0x86E4

gl_RGBA_UNSIGNED_DOT_PRODUCT_MAPPING_NV :: GLenum
gl_RGBA_UNSIGNED_DOT_PRODUCT_MAPPING_NV = 0x86D9

gl_SHADER_CONSISTENT_NV :: GLenum
gl_SHADER_CONSISTENT_NV = 0x86DD

gl_SHADER_OPERATION_NV :: GLenum
gl_SHADER_OPERATION_NV = 0x86DF

gl_SIGNED_ALPHA8_NV :: GLenum
gl_SIGNED_ALPHA8_NV = 0x8706

gl_SIGNED_ALPHA_NV :: GLenum
gl_SIGNED_ALPHA_NV = 0x8705

gl_SIGNED_HILO16_NV :: GLenum
gl_SIGNED_HILO16_NV = 0x86FA

gl_SIGNED_HILO_NV :: GLenum
gl_SIGNED_HILO_NV = 0x86F9

gl_SIGNED_INTENSITY8_NV :: GLenum
gl_SIGNED_INTENSITY8_NV = 0x8708

gl_SIGNED_INTENSITY_NV :: GLenum
gl_SIGNED_INTENSITY_NV = 0x8707

gl_SIGNED_LUMINANCE8_ALPHA8_NV :: GLenum
gl_SIGNED_LUMINANCE8_ALPHA8_NV = 0x8704

gl_SIGNED_LUMINANCE8_NV :: GLenum
gl_SIGNED_LUMINANCE8_NV = 0x8702

gl_SIGNED_LUMINANCE_ALPHA_NV :: GLenum
gl_SIGNED_LUMINANCE_ALPHA_NV = 0x8703

gl_SIGNED_LUMINANCE_NV :: GLenum
gl_SIGNED_LUMINANCE_NV = 0x8701

gl_SIGNED_RGB8_NV :: GLenum
gl_SIGNED_RGB8_NV = 0x86FF

gl_SIGNED_RGB8_UNSIGNED_ALPHA8_NV :: GLenum
gl_SIGNED_RGB8_UNSIGNED_ALPHA8_NV = 0x870D

gl_SIGNED_RGBA8_NV :: GLenum
gl_SIGNED_RGBA8_NV = 0x86FC

gl_SIGNED_RGBA_NV :: GLenum
gl_SIGNED_RGBA_NV = 0x86FB

gl_SIGNED_RGB_NV :: GLenum
gl_SIGNED_RGB_NV = 0x86FE

gl_SIGNED_RGB_UNSIGNED_ALPHA_NV :: GLenum
gl_SIGNED_RGB_UNSIGNED_ALPHA_NV = 0x870C

gl_TEXTURE_BORDER_VALUES_NV :: GLenum
gl_TEXTURE_BORDER_VALUES_NV = 0x871A

gl_TEXTURE_DS_SIZE_NV :: GLenum
gl_TEXTURE_DS_SIZE_NV = 0x871D

gl_TEXTURE_DT_SIZE_NV :: GLenum
gl_TEXTURE_DT_SIZE_NV = 0x871E

gl_TEXTURE_HI_SIZE_NV :: GLenum
gl_TEXTURE_HI_SIZE_NV = 0x871B

gl_TEXTURE_LO_SIZE_NV :: GLenum
gl_TEXTURE_LO_SIZE_NV = 0x871C

gl_TEXTURE_MAG_SIZE_NV :: GLenum
gl_TEXTURE_MAG_SIZE_NV = 0x871F

gl_TEXTURE_SHADER_NV :: GLenum
gl_TEXTURE_SHADER_NV = 0x86DE

gl_UNSIGNED_INT_8_8_S8_S8_REV_NV :: GLenum
gl_UNSIGNED_INT_8_8_S8_S8_REV_NV = 0x86DB

gl_UNSIGNED_INT_S8_S8_8_8_NV :: GLenum
gl_UNSIGNED_INT_S8_S8_8_8_NV = 0x86DA

gl_VIBRANCE_BIAS_NV :: GLenum
gl_VIBRANCE_BIAS_NV = 0x8719

gl_VIBRANCE_SCALE_NV :: GLenum
gl_VIBRANCE_SCALE_NV = 0x8713