-- This file was automatically generated.
module Graphics.OpenGL.Extension.NV.TextureShader3 (
	-- * Extension Support
	  gl_NV_texture_shader3

	-- * GL_NV_texture_shader3
	, gl_DEPENDENT_HILO_TEXTURE_2D_NV
	, gl_DEPENDENT_RGB_TEXTURE_3D_NV
	, gl_DEPENDENT_RGB_TEXTURE_CUBE_MAP_NV
	, gl_DOT_PRODUCT_AFFINE_DEPTH_REPLACE_NV
	, gl_DOT_PRODUCT_PASS_THROUGH_NV
	, gl_DOT_PRODUCT_TEXTURE_1D_NV
	, gl_FORCE_BLUE_TO_ONE_NV
	, gl_HILO8_NV
	, gl_OFFSET_HILO_PROJECTIVE_TEXTURE_2D_NV
	, gl_OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE_NV
	, gl_OFFSET_HILO_TEXTURE_2D_NV
	, gl_OFFSET_HILO_TEXTURE_RECTANGLE_NV
	, gl_OFFSET_PROJECTIVE_TEXTURE_2D_NV
	, gl_OFFSET_PROJECTIVE_TEXTURE_2D_SCALE_NV
	, gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_NV
	, gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE_NV
	, gl_SIGNED_HILO8_NV
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

gl_NV_texture_shader3 :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_NV_texture_shader3 = extGL 526

gl_DEPENDENT_HILO_TEXTURE_2D_NV :: GLenum
gl_DEPENDENT_HILO_TEXTURE_2D_NV = 0x8858

gl_DEPENDENT_RGB_TEXTURE_3D_NV :: GLenum
gl_DEPENDENT_RGB_TEXTURE_3D_NV = 0x8859

gl_DEPENDENT_RGB_TEXTURE_CUBE_MAP_NV :: GLenum
gl_DEPENDENT_RGB_TEXTURE_CUBE_MAP_NV = 0x885A

gl_DOT_PRODUCT_AFFINE_DEPTH_REPLACE_NV :: GLenum
gl_DOT_PRODUCT_AFFINE_DEPTH_REPLACE_NV = 0x885D

gl_DOT_PRODUCT_PASS_THROUGH_NV :: GLenum
gl_DOT_PRODUCT_PASS_THROUGH_NV = 0x885B

gl_DOT_PRODUCT_TEXTURE_1D_NV :: GLenum
gl_DOT_PRODUCT_TEXTURE_1D_NV = 0x885C

gl_FORCE_BLUE_TO_ONE_NV :: GLenum
gl_FORCE_BLUE_TO_ONE_NV = 0x8860

gl_HILO8_NV :: GLenum
gl_HILO8_NV = 0x885E

gl_OFFSET_HILO_PROJECTIVE_TEXTURE_2D_NV :: GLenum
gl_OFFSET_HILO_PROJECTIVE_TEXTURE_2D_NV = 0x8856

gl_OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE_NV :: GLenum
gl_OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE_NV = 0x8857

gl_OFFSET_HILO_TEXTURE_2D_NV :: GLenum
gl_OFFSET_HILO_TEXTURE_2D_NV = 0x8854

gl_OFFSET_HILO_TEXTURE_RECTANGLE_NV :: GLenum
gl_OFFSET_HILO_TEXTURE_RECTANGLE_NV = 0x8855

gl_OFFSET_PROJECTIVE_TEXTURE_2D_NV :: GLenum
gl_OFFSET_PROJECTIVE_TEXTURE_2D_NV = 0x8850

gl_OFFSET_PROJECTIVE_TEXTURE_2D_SCALE_NV :: GLenum
gl_OFFSET_PROJECTIVE_TEXTURE_2D_SCALE_NV = 0x8851

gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_NV :: GLenum
gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_NV = 0x8852

gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE_NV :: GLenum
gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE_NV = 0x8853

gl_SIGNED_HILO8_NV :: GLenum
gl_SIGNED_HILO8_NV = 0x885F