-- This file was automatically generated.
module Graphics.OpenGL.Extension.EXT.GeometryShader4 (
	-- * Extension Support
	  gl_EXT_geometry_shader4

	-- * GL_EXT_geometry_shader4
	, glProgramParameteriEXT
	, gl_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT
	, gl_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER_EXT
	, gl_FRAMEBUFFER_INCOMPLETE_LAYER_COUNT_EXT
	, gl_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_EXT
	, gl_GEOMETRY_INPUT_TYPE_EXT
	, gl_GEOMETRY_OUTPUT_TYPE_EXT
	, gl_GEOMETRY_SHADER_EXT
	, gl_GEOMETRY_VERTICES_OUT_EXT
	, gl_LINES_ADJACENCY_EXT
	, gl_LINE_STRIP_ADJACENCY_EXT
	, gl_MAX_GEOMETRY_OUTPUT_VERTICES_EXT
	, gl_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT
	, gl_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_EXT
	, gl_MAX_GEOMETRY_UNIFORM_COMPONENTS_EXT
	, gl_MAX_GEOMETRY_VARYING_COMPONENTS_EXT
	, gl_MAX_VARYING_COMPONENTS_EXT
	, gl_MAX_VERTEX_VARYING_COMPONENTS_EXT
	, gl_PROGRAM_POINT_SIZE_EXT
	, gl_TRIANGLES_ADJACENCY_EXT
	, gl_TRIANGLE_STRIP_ADJACENCY_EXT
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

import Graphics.OpenGL.Internal.Shared

gl_EXT_geometry_shader4 :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_EXT_geometry_shader4 = extGL 285

gl_MAX_GEOMETRY_VARYING_COMPONENTS_EXT :: GLenum
gl_MAX_GEOMETRY_VARYING_COMPONENTS_EXT = 0x8DDD

gl_MAX_VARYING_COMPONENTS_EXT :: GLenum
gl_MAX_VARYING_COMPONENTS_EXT = 0x8B4B

gl_MAX_VERTEX_VARYING_COMPONENTS_EXT :: GLenum
gl_MAX_VERTEX_VARYING_COMPONENTS_EXT = 0x8DDE