-- This file was automatically generated.
module Graphics.OpenGL.Extension.EXT.GeometryShader (
	-- * Extension Support
	  gl_EXT_geometry_shader

	-- * GL_EXT_geometry_shader
	, glFramebufferTextureEXT
	, gl_FIRST_VERTEX_CONVENTION_EXT
	, gl_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT
	, gl_FRAMEBUFFER_DEFAULT_LAYERS_EXT
	, gl_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_EXT
	, gl_GEOMETRY_LINKED_INPUT_TYPE_EXT
	, gl_GEOMETRY_LINKED_OUTPUT_TYPE_EXT
	, gl_GEOMETRY_LINKED_VERTICES_OUT_EXT
	, gl_GEOMETRY_SHADER_BIT_EXT
	, gl_GEOMETRY_SHADER_EXT
	, gl_GEOMETRY_SHADER_INVOCATIONS_EXT
	, gl_LAST_VERTEX_CONVENTION_EXT
	, gl_LAYER_PROVOKING_VERTEX_EXT
	, gl_LINES_ADJACENCY_EXT
	, gl_LINE_STRIP_ADJACENCY_EXT
	, gl_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS_EXT
	, gl_MAX_FRAMEBUFFER_LAYERS_EXT
	, gl_MAX_GEOMETRY_ATOMIC_COUNTERS_EXT
	, gl_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS_EXT
	, gl_MAX_GEOMETRY_IMAGE_UNIFORMS_EXT
	, gl_MAX_GEOMETRY_INPUT_COMPONENTS_EXT
	, gl_MAX_GEOMETRY_OUTPUT_COMPONENTS_EXT
	, gl_MAX_GEOMETRY_OUTPUT_VERTICES_EXT
	, gl_MAX_GEOMETRY_SHADER_INVOCATIONS_EXT
	, gl_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS_EXT
	, gl_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT
	, gl_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_EXT
	, gl_MAX_GEOMETRY_UNIFORM_BLOCKS_EXT
	, gl_MAX_GEOMETRY_UNIFORM_COMPONENTS_EXT
	, gl_PRIMITIVES_GENERATED_EXT
	, gl_REFERENCED_BY_GEOMETRY_SHADER_EXT
	, gl_TRIANGLES_ADJACENCY_EXT
	, gl_TRIANGLE_STRIP_ADJACENCY_EXT
	, gl_UNDEFINED_VERTEX_EXT
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

import Graphics.OpenGL.Internal.Shared

gl_EXT_geometry_shader :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_EXT_geometry_shader = extGL 284

gl_FRAMEBUFFER_DEFAULT_LAYERS_EXT :: GLenum
gl_FRAMEBUFFER_DEFAULT_LAYERS_EXT = 0x9312

gl_GEOMETRY_LINKED_INPUT_TYPE_EXT :: GLenum
gl_GEOMETRY_LINKED_INPUT_TYPE_EXT = 0x8917

gl_GEOMETRY_LINKED_OUTPUT_TYPE_EXT :: GLenum
gl_GEOMETRY_LINKED_OUTPUT_TYPE_EXT = 0x8918

gl_GEOMETRY_LINKED_VERTICES_OUT_EXT :: GLenum
gl_GEOMETRY_LINKED_VERTICES_OUT_EXT = 0x8916

gl_GEOMETRY_SHADER_BIT_EXT :: GLenum
gl_GEOMETRY_SHADER_BIT_EXT = 0x00000004

gl_GEOMETRY_SHADER_INVOCATIONS_EXT :: GLenum
gl_GEOMETRY_SHADER_INVOCATIONS_EXT = 0x887F

gl_LAYER_PROVOKING_VERTEX_EXT :: GLenum
gl_LAYER_PROVOKING_VERTEX_EXT = 0x825E

gl_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS_EXT :: GLenum
gl_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS_EXT = 0x8A32

gl_MAX_FRAMEBUFFER_LAYERS_EXT :: GLenum
gl_MAX_FRAMEBUFFER_LAYERS_EXT = 0x9317

gl_MAX_GEOMETRY_ATOMIC_COUNTERS_EXT :: GLenum
gl_MAX_GEOMETRY_ATOMIC_COUNTERS_EXT = 0x92D5

gl_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS_EXT :: GLenum
gl_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS_EXT = 0x92CF

gl_MAX_GEOMETRY_IMAGE_UNIFORMS_EXT :: GLenum
gl_MAX_GEOMETRY_IMAGE_UNIFORMS_EXT = 0x90CD

gl_MAX_GEOMETRY_INPUT_COMPONENTS_EXT :: GLenum
gl_MAX_GEOMETRY_INPUT_COMPONENTS_EXT = 0x9123

gl_MAX_GEOMETRY_OUTPUT_COMPONENTS_EXT :: GLenum
gl_MAX_GEOMETRY_OUTPUT_COMPONENTS_EXT = 0x9124

gl_MAX_GEOMETRY_SHADER_INVOCATIONS_EXT :: GLenum
gl_MAX_GEOMETRY_SHADER_INVOCATIONS_EXT = 0x8E5A

gl_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS_EXT :: GLenum
gl_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS_EXT = 0x90D7

gl_MAX_GEOMETRY_UNIFORM_BLOCKS_EXT :: GLenum
gl_MAX_GEOMETRY_UNIFORM_BLOCKS_EXT = 0x8A2C

gl_REFERENCED_BY_GEOMETRY_SHADER_EXT :: GLenum
gl_REFERENCED_BY_GEOMETRY_SHADER_EXT = 0x9309

gl_UNDEFINED_VERTEX_EXT :: GLenum
gl_UNDEFINED_VERTEX_EXT = 0x8260