-- This file was automatically generated.
module Graphics.OpenGL.Extension.EXT.PvrtcSRGB (
	-- * Extension Support
	  gl_EXT_pvrtc_sRGB

	-- * GL_EXT_pvrtc_sRGB
	, gl_COMPRESSED_SRGB_ALPHA_PVRTC_2BPPV1_EXT
	, gl_COMPRESSED_SRGB_ALPHA_PVRTC_2BPPV2_IMG
	, gl_COMPRESSED_SRGB_ALPHA_PVRTC_4BPPV1_EXT
	, gl_COMPRESSED_SRGB_ALPHA_PVRTC_4BPPV2_IMG
	, gl_COMPRESSED_SRGB_PVRTC_2BPPV1_EXT
	, gl_COMPRESSED_SRGB_PVRTC_4BPPV1_EXT
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

gl_EXT_pvrtc_sRGB :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_EXT_pvrtc_sRGB = extGL 316

gl_COMPRESSED_SRGB_ALPHA_PVRTC_2BPPV1_EXT :: GLenum
gl_COMPRESSED_SRGB_ALPHA_PVRTC_2BPPV1_EXT = 0x8A56

gl_COMPRESSED_SRGB_ALPHA_PVRTC_2BPPV2_IMG :: GLenum
gl_COMPRESSED_SRGB_ALPHA_PVRTC_2BPPV2_IMG = 0x93F0

gl_COMPRESSED_SRGB_ALPHA_PVRTC_4BPPV1_EXT :: GLenum
gl_COMPRESSED_SRGB_ALPHA_PVRTC_4BPPV1_EXT = 0x8A57

gl_COMPRESSED_SRGB_ALPHA_PVRTC_4BPPV2_IMG :: GLenum
gl_COMPRESSED_SRGB_ALPHA_PVRTC_4BPPV2_IMG = 0x93F1

gl_COMPRESSED_SRGB_PVRTC_2BPPV1_EXT :: GLenum
gl_COMPRESSED_SRGB_PVRTC_2BPPV1_EXT = 0x8A54

gl_COMPRESSED_SRGB_PVRTC_4BPPV1_EXT :: GLenum
gl_COMPRESSED_SRGB_PVRTC_4BPPV1_EXT = 0x8A55