-- This file was automatically generated.
module Graphics.OpenGL.Extension.EXT.ShaderImageLoadStore (
	-- * Extension Support
	  gl_EXT_shader_image_load_store

	-- * GL_EXT_shader_image_load_store
	, glBindImageTextureEXT
	, glMemoryBarrierEXT
	, gl_ALL_BARRIER_BITS_EXT
	, gl_ATOMIC_COUNTER_BARRIER_BIT_EXT
	, gl_BUFFER_UPDATE_BARRIER_BIT_EXT
	, gl_COMMAND_BARRIER_BIT_EXT
	, gl_ELEMENT_ARRAY_BARRIER_BIT_EXT
	, gl_FRAMEBUFFER_BARRIER_BIT_EXT
	, gl_IMAGE_1D_ARRAY_EXT
	, gl_IMAGE_1D_EXT
	, gl_IMAGE_2D_ARRAY_EXT
	, gl_IMAGE_2D_EXT
	, gl_IMAGE_2D_MULTISAMPLE_ARRAY_EXT
	, gl_IMAGE_2D_MULTISAMPLE_EXT
	, gl_IMAGE_2D_RECT_EXT
	, gl_IMAGE_3D_EXT
	, gl_IMAGE_BINDING_ACCESS_EXT
	, gl_IMAGE_BINDING_FORMAT_EXT
	, gl_IMAGE_BINDING_LAYERED_EXT
	, gl_IMAGE_BINDING_LAYER_EXT
	, gl_IMAGE_BINDING_LEVEL_EXT
	, gl_IMAGE_BINDING_NAME_EXT
	, gl_IMAGE_BUFFER_EXT
	, gl_IMAGE_CUBE_EXT
	, gl_IMAGE_CUBE_MAP_ARRAY_EXT
	, gl_INT_IMAGE_1D_ARRAY_EXT
	, gl_INT_IMAGE_1D_EXT
	, gl_INT_IMAGE_2D_ARRAY_EXT
	, gl_INT_IMAGE_2D_EXT
	, gl_INT_IMAGE_2D_MULTISAMPLE_ARRAY_EXT
	, gl_INT_IMAGE_2D_MULTISAMPLE_EXT
	, gl_INT_IMAGE_2D_RECT_EXT
	, gl_INT_IMAGE_3D_EXT
	, gl_INT_IMAGE_BUFFER_EXT
	, gl_INT_IMAGE_CUBE_EXT
	, gl_INT_IMAGE_CUBE_MAP_ARRAY_EXT
	, gl_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS_EXT
	, gl_MAX_IMAGE_SAMPLES_EXT
	, gl_MAX_IMAGE_UNITS_EXT
	, gl_PIXEL_BUFFER_BARRIER_BIT_EXT
	, gl_SHADER_IMAGE_ACCESS_BARRIER_BIT_EXT
	, gl_TEXTURE_FETCH_BARRIER_BIT_EXT
	, gl_TEXTURE_UPDATE_BARRIER_BIT_EXT
	, gl_TRANSFORM_FEEDBACK_BARRIER_BIT_EXT
	, gl_UNIFORM_BARRIER_BIT_EXT
	, gl_UNSIGNED_INT_IMAGE_1D_ARRAY_EXT
	, gl_UNSIGNED_INT_IMAGE_1D_EXT
	, gl_UNSIGNED_INT_IMAGE_2D_ARRAY_EXT
	, gl_UNSIGNED_INT_IMAGE_2D_EXT
	, gl_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY_EXT
	, gl_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_EXT
	, gl_UNSIGNED_INT_IMAGE_2D_RECT_EXT
	, gl_UNSIGNED_INT_IMAGE_3D_EXT
	, gl_UNSIGNED_INT_IMAGE_BUFFER_EXT
	, gl_UNSIGNED_INT_IMAGE_CUBE_EXT
	, gl_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY_EXT
	, gl_VERTEX_ATTRIB_ARRAY_BARRIER_BIT_EXT
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

import Graphics.OpenGL.Internal.Shared

gl_EXT_shader_image_load_store :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_EXT_shader_image_load_store = extGL 328

glBindImageTextureEXT :: (MonadIO m, MonadReader e m, HasScope e) => GLuint -> GLuint -> GLint -> GLboolean -> GLint -> GLenum -> GLint -> m ()
glBindImageTextureEXT v0 v1 v2 v3 v4 v5 v6 = funGL 1357 >>= \f -> liftIO $ f v0 v1 v2 v3 v4 v5 v6

glMemoryBarrierEXT :: (MonadIO m, MonadReader e m, HasScope e) => GLbitfield -> m ()
glMemoryBarrierEXT v0 = funGL 1358 >>= \f -> liftIO $ f v0

gl_ALL_BARRIER_BITS_EXT :: GLenum
gl_ALL_BARRIER_BITS_EXT = 0xFFFFFFFF

gl_ATOMIC_COUNTER_BARRIER_BIT_EXT :: GLenum
gl_ATOMIC_COUNTER_BARRIER_BIT_EXT = 0x00001000

gl_BUFFER_UPDATE_BARRIER_BIT_EXT :: GLenum
gl_BUFFER_UPDATE_BARRIER_BIT_EXT = 0x00000200

gl_COMMAND_BARRIER_BIT_EXT :: GLenum
gl_COMMAND_BARRIER_BIT_EXT = 0x00000040

gl_ELEMENT_ARRAY_BARRIER_BIT_EXT :: GLenum
gl_ELEMENT_ARRAY_BARRIER_BIT_EXT = 0x00000002

gl_FRAMEBUFFER_BARRIER_BIT_EXT :: GLenum
gl_FRAMEBUFFER_BARRIER_BIT_EXT = 0x00000400

gl_IMAGE_1D_ARRAY_EXT :: GLenum
gl_IMAGE_1D_ARRAY_EXT = 0x9052

gl_IMAGE_1D_EXT :: GLenum
gl_IMAGE_1D_EXT = 0x904C

gl_IMAGE_2D_ARRAY_EXT :: GLenum
gl_IMAGE_2D_ARRAY_EXT = 0x9053

gl_IMAGE_2D_EXT :: GLenum
gl_IMAGE_2D_EXT = 0x904D

gl_IMAGE_2D_MULTISAMPLE_ARRAY_EXT :: GLenum
gl_IMAGE_2D_MULTISAMPLE_ARRAY_EXT = 0x9056

gl_IMAGE_2D_MULTISAMPLE_EXT :: GLenum
gl_IMAGE_2D_MULTISAMPLE_EXT = 0x9055

gl_IMAGE_2D_RECT_EXT :: GLenum
gl_IMAGE_2D_RECT_EXT = 0x904F

gl_IMAGE_3D_EXT :: GLenum
gl_IMAGE_3D_EXT = 0x904E

gl_IMAGE_BINDING_ACCESS_EXT :: GLenum
gl_IMAGE_BINDING_ACCESS_EXT = 0x8F3E

gl_IMAGE_BINDING_FORMAT_EXT :: GLenum
gl_IMAGE_BINDING_FORMAT_EXT = 0x906E

gl_IMAGE_BINDING_LAYERED_EXT :: GLenum
gl_IMAGE_BINDING_LAYERED_EXT = 0x8F3C

gl_IMAGE_BINDING_LAYER_EXT :: GLenum
gl_IMAGE_BINDING_LAYER_EXT = 0x8F3D

gl_IMAGE_BINDING_LEVEL_EXT :: GLenum
gl_IMAGE_BINDING_LEVEL_EXT = 0x8F3B

gl_IMAGE_BINDING_NAME_EXT :: GLenum
gl_IMAGE_BINDING_NAME_EXT = 0x8F3A

gl_IMAGE_CUBE_EXT :: GLenum
gl_IMAGE_CUBE_EXT = 0x9050

gl_INT_IMAGE_1D_ARRAY_EXT :: GLenum
gl_INT_IMAGE_1D_ARRAY_EXT = 0x905D

gl_INT_IMAGE_1D_EXT :: GLenum
gl_INT_IMAGE_1D_EXT = 0x9057

gl_INT_IMAGE_2D_ARRAY_EXT :: GLenum
gl_INT_IMAGE_2D_ARRAY_EXT = 0x905E

gl_INT_IMAGE_2D_EXT :: GLenum
gl_INT_IMAGE_2D_EXT = 0x9058

gl_INT_IMAGE_2D_MULTISAMPLE_ARRAY_EXT :: GLenum
gl_INT_IMAGE_2D_MULTISAMPLE_ARRAY_EXT = 0x9061

gl_INT_IMAGE_2D_MULTISAMPLE_EXT :: GLenum
gl_INT_IMAGE_2D_MULTISAMPLE_EXT = 0x9060

gl_INT_IMAGE_2D_RECT_EXT :: GLenum
gl_INT_IMAGE_2D_RECT_EXT = 0x905A

gl_INT_IMAGE_3D_EXT :: GLenum
gl_INT_IMAGE_3D_EXT = 0x9059

gl_INT_IMAGE_CUBE_EXT :: GLenum
gl_INT_IMAGE_CUBE_EXT = 0x905B

gl_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS_EXT :: GLenum
gl_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS_EXT = 0x8F39

gl_MAX_IMAGE_SAMPLES_EXT :: GLenum
gl_MAX_IMAGE_SAMPLES_EXT = 0x906D

gl_MAX_IMAGE_UNITS_EXT :: GLenum
gl_MAX_IMAGE_UNITS_EXT = 0x8F38

gl_PIXEL_BUFFER_BARRIER_BIT_EXT :: GLenum
gl_PIXEL_BUFFER_BARRIER_BIT_EXT = 0x00000080

gl_SHADER_IMAGE_ACCESS_BARRIER_BIT_EXT :: GLenum
gl_SHADER_IMAGE_ACCESS_BARRIER_BIT_EXT = 0x00000020

gl_TEXTURE_FETCH_BARRIER_BIT_EXT :: GLenum
gl_TEXTURE_FETCH_BARRIER_BIT_EXT = 0x00000008

gl_TEXTURE_UPDATE_BARRIER_BIT_EXT :: GLenum
gl_TEXTURE_UPDATE_BARRIER_BIT_EXT = 0x00000100

gl_TRANSFORM_FEEDBACK_BARRIER_BIT_EXT :: GLenum
gl_TRANSFORM_FEEDBACK_BARRIER_BIT_EXT = 0x00000800

gl_UNIFORM_BARRIER_BIT_EXT :: GLenum
gl_UNIFORM_BARRIER_BIT_EXT = 0x00000004

gl_UNSIGNED_INT_IMAGE_1D_ARRAY_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_1D_ARRAY_EXT = 0x9068

gl_UNSIGNED_INT_IMAGE_1D_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_1D_EXT = 0x9062

gl_UNSIGNED_INT_IMAGE_2D_ARRAY_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_2D_ARRAY_EXT = 0x9069

gl_UNSIGNED_INT_IMAGE_2D_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_2D_EXT = 0x9063

gl_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY_EXT = 0x906C

gl_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_EXT = 0x906B

gl_UNSIGNED_INT_IMAGE_2D_RECT_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_2D_RECT_EXT = 0x9065

gl_UNSIGNED_INT_IMAGE_3D_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_3D_EXT = 0x9064

gl_UNSIGNED_INT_IMAGE_CUBE_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_CUBE_EXT = 0x9066

gl_VERTEX_ATTRIB_ARRAY_BARRIER_BIT_EXT :: GLenum
gl_VERTEX_ATTRIB_ARRAY_BARRIER_BIT_EXT = 0x00000001