-- This file was automatically generated.
module Graphics.OpenGL.Extension.EXT.TessellationShader (
	-- * Extension Support
	  gl_EXT_tessellation_shader

	-- * GL_EXT_tessellation_shader
	, glPatchParameteriEXT
	, gl_CCW
	, gl_CW
	, gl_EQUAL
	, gl_FRACTIONAL_EVEN_EXT
	, gl_FRACTIONAL_ODD_EXT
	, gl_ISOLINES_EXT
	, gl_IS_PER_PATCH_EXT
	, gl_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS_EXT
	, gl_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS_EXT
	, gl_MAX_PATCH_VERTICES_EXT
	, gl_MAX_TESS_CONTROL_ATOMIC_COUNTERS_EXT
	, gl_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS_EXT
	, gl_MAX_TESS_CONTROL_IMAGE_UNIFORMS_EXT
	, gl_MAX_TESS_CONTROL_INPUT_COMPONENTS_EXT
	, gl_MAX_TESS_CONTROL_OUTPUT_COMPONENTS_EXT
	, gl_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS_EXT
	, gl_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS_EXT
	, gl_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS_EXT
	, gl_MAX_TESS_CONTROL_UNIFORM_BLOCKS_EXT
	, gl_MAX_TESS_CONTROL_UNIFORM_COMPONENTS_EXT
	, gl_MAX_TESS_EVALUATION_ATOMIC_COUNTERS_EXT
	, gl_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS_EXT
	, gl_MAX_TESS_EVALUATION_IMAGE_UNIFORMS_EXT
	, gl_MAX_TESS_EVALUATION_INPUT_COMPONENTS_EXT
	, gl_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS_EXT
	, gl_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS_EXT
	, gl_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS_EXT
	, gl_MAX_TESS_EVALUATION_UNIFORM_BLOCKS_EXT
	, gl_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS_EXT
	, gl_MAX_TESS_GEN_LEVEL_EXT
	, gl_MAX_TESS_PATCH_COMPONENTS_EXT
	, gl_PATCHES_EXT
	, gl_PATCH_VERTICES_EXT
	, gl_PRIMITIVE_RESTART_FOR_PATCHES_SUPPORTED
	, gl_QUADS_EXT
	, gl_REFERENCED_BY_TESS_CONTROL_SHADER_EXT
	, gl_REFERENCED_BY_TESS_EVALUATION_SHADER_EXT
	, gl_TESS_CONTROL_OUTPUT_VERTICES_EXT
	, gl_TESS_CONTROL_SHADER_BIT_EXT
	, gl_TESS_CONTROL_SHADER_EXT
	, gl_TESS_EVALUATION_SHADER_BIT_EXT
	, gl_TESS_EVALUATION_SHADER_EXT
	, gl_TESS_GEN_MODE_EXT
	, gl_TESS_GEN_POINT_MODE_EXT
	, gl_TESS_GEN_SPACING_EXT
	, gl_TESS_GEN_VERTEX_ORDER_EXT
	, gl_TRIANGLES
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

import Graphics.OpenGL.Internal.Shared

gl_EXT_tessellation_shader :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_EXT_tessellation_shader = extGL 343

glPatchParameteriEXT :: (MonadIO m, MonadReader e m, HasScope e) => GLenum -> GLint -> m ()
glPatchParameteriEXT v0 v1 = funGL 1363 >>= \f -> liftIO $ f v0 v1

gl_FRACTIONAL_EVEN_EXT :: GLenum
gl_FRACTIONAL_EVEN_EXT = 0x8E7C

gl_FRACTIONAL_ODD_EXT :: GLenum
gl_FRACTIONAL_ODD_EXT = 0x8E7B

gl_ISOLINES_EXT :: GLenum
gl_ISOLINES_EXT = 0x8E7A

gl_IS_PER_PATCH_EXT :: GLenum
gl_IS_PER_PATCH_EXT = 0x92E7

gl_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS_EXT :: GLenum
gl_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS_EXT = 0x8E1E

gl_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS_EXT :: GLenum
gl_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS_EXT = 0x8E1F

gl_MAX_PATCH_VERTICES_EXT :: GLenum
gl_MAX_PATCH_VERTICES_EXT = 0x8E7D

gl_MAX_TESS_CONTROL_ATOMIC_COUNTERS_EXT :: GLenum
gl_MAX_TESS_CONTROL_ATOMIC_COUNTERS_EXT = 0x92D3

gl_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS_EXT :: GLenum
gl_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS_EXT = 0x92CD

gl_MAX_TESS_CONTROL_IMAGE_UNIFORMS_EXT :: GLenum
gl_MAX_TESS_CONTROL_IMAGE_UNIFORMS_EXT = 0x90CB

gl_MAX_TESS_CONTROL_INPUT_COMPONENTS_EXT :: GLenum
gl_MAX_TESS_CONTROL_INPUT_COMPONENTS_EXT = 0x886C

gl_MAX_TESS_CONTROL_OUTPUT_COMPONENTS_EXT :: GLenum
gl_MAX_TESS_CONTROL_OUTPUT_COMPONENTS_EXT = 0x8E83

gl_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS_EXT :: GLenum
gl_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS_EXT = 0x90D8

gl_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS_EXT :: GLenum
gl_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS_EXT = 0x8E81

gl_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS_EXT :: GLenum
gl_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS_EXT = 0x8E85

gl_MAX_TESS_CONTROL_UNIFORM_BLOCKS_EXT :: GLenum
gl_MAX_TESS_CONTROL_UNIFORM_BLOCKS_EXT = 0x8E89

gl_MAX_TESS_CONTROL_UNIFORM_COMPONENTS_EXT :: GLenum
gl_MAX_TESS_CONTROL_UNIFORM_COMPONENTS_EXT = 0x8E7F

gl_MAX_TESS_EVALUATION_ATOMIC_COUNTERS_EXT :: GLenum
gl_MAX_TESS_EVALUATION_ATOMIC_COUNTERS_EXT = 0x92D4

gl_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS_EXT :: GLenum
gl_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS_EXT = 0x92CE

gl_MAX_TESS_EVALUATION_IMAGE_UNIFORMS_EXT :: GLenum
gl_MAX_TESS_EVALUATION_IMAGE_UNIFORMS_EXT = 0x90CC

gl_MAX_TESS_EVALUATION_INPUT_COMPONENTS_EXT :: GLenum
gl_MAX_TESS_EVALUATION_INPUT_COMPONENTS_EXT = 0x886D

gl_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS_EXT :: GLenum
gl_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS_EXT = 0x8E86

gl_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS_EXT :: GLenum
gl_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS_EXT = 0x90D9

gl_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS_EXT :: GLenum
gl_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS_EXT = 0x8E82

gl_MAX_TESS_EVALUATION_UNIFORM_BLOCKS_EXT :: GLenum
gl_MAX_TESS_EVALUATION_UNIFORM_BLOCKS_EXT = 0x8E8A

gl_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS_EXT :: GLenum
gl_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS_EXT = 0x8E80

gl_MAX_TESS_GEN_LEVEL_EXT :: GLenum
gl_MAX_TESS_GEN_LEVEL_EXT = 0x8E7E

gl_MAX_TESS_PATCH_COMPONENTS_EXT :: GLenum
gl_MAX_TESS_PATCH_COMPONENTS_EXT = 0x8E84

gl_PATCHES_EXT :: GLenum
gl_PATCHES_EXT = 0x000E

gl_PATCH_VERTICES_EXT :: GLenum
gl_PATCH_VERTICES_EXT = 0x8E72

gl_QUADS_EXT :: GLenum
gl_QUADS_EXT = 0x0007

gl_REFERENCED_BY_TESS_CONTROL_SHADER_EXT :: GLenum
gl_REFERENCED_BY_TESS_CONTROL_SHADER_EXT = 0x9307

gl_REFERENCED_BY_TESS_EVALUATION_SHADER_EXT :: GLenum
gl_REFERENCED_BY_TESS_EVALUATION_SHADER_EXT = 0x9308

gl_TESS_CONTROL_OUTPUT_VERTICES_EXT :: GLenum
gl_TESS_CONTROL_OUTPUT_VERTICES_EXT = 0x8E75

gl_TESS_CONTROL_SHADER_BIT_EXT :: GLenum
gl_TESS_CONTROL_SHADER_BIT_EXT = 0x00000008

gl_TESS_CONTROL_SHADER_EXT :: GLenum
gl_TESS_CONTROL_SHADER_EXT = 0x8E88

gl_TESS_EVALUATION_SHADER_BIT_EXT :: GLenum
gl_TESS_EVALUATION_SHADER_BIT_EXT = 0x00000010

gl_TESS_EVALUATION_SHADER_EXT :: GLenum
gl_TESS_EVALUATION_SHADER_EXT = 0x8E87

gl_TESS_GEN_MODE_EXT :: GLenum
gl_TESS_GEN_MODE_EXT = 0x8E76

gl_TESS_GEN_POINT_MODE_EXT :: GLenum
gl_TESS_GEN_POINT_MODE_EXT = 0x8E79

gl_TESS_GEN_SPACING_EXT :: GLenum
gl_TESS_GEN_SPACING_EXT = 0x8E77

gl_TESS_GEN_VERTEX_ORDER_EXT :: GLenum
gl_TESS_GEN_VERTEX_ORDER_EXT = 0x8E78