-- This file was automatically generated.
module Graphics.OpenGL.Extension.EXT.TextureInteger (
	-- * Extension Support
	  gl_EXT_texture_integer

	-- * GL_EXT_texture_integer
	, glClearColorIiEXT
	, glClearColorIuiEXT
	, glGetTexParameterIivEXT
	, glGetTexParameterIuivEXT
	, glTexParameterIivEXT
	, glTexParameterIuivEXT
	, gl_ALPHA16I_EXT
	, gl_ALPHA16UI_EXT
	, gl_ALPHA32I_EXT
	, gl_ALPHA32UI_EXT
	, gl_ALPHA8I_EXT
	, gl_ALPHA8UI_EXT
	, gl_ALPHA_INTEGER_EXT
	, gl_BGRA_INTEGER_EXT
	, gl_BGR_INTEGER_EXT
	, gl_BLUE_INTEGER_EXT
	, gl_GREEN_INTEGER_EXT
	, gl_INTENSITY16I_EXT
	, gl_INTENSITY16UI_EXT
	, gl_INTENSITY32I_EXT
	, gl_INTENSITY32UI_EXT
	, gl_INTENSITY8I_EXT
	, gl_INTENSITY8UI_EXT
	, gl_LUMINANCE16I_EXT
	, gl_LUMINANCE16UI_EXT
	, gl_LUMINANCE32I_EXT
	, gl_LUMINANCE32UI_EXT
	, gl_LUMINANCE8I_EXT
	, gl_LUMINANCE8UI_EXT
	, gl_LUMINANCE_ALPHA16I_EXT
	, gl_LUMINANCE_ALPHA16UI_EXT
	, gl_LUMINANCE_ALPHA32I_EXT
	, gl_LUMINANCE_ALPHA32UI_EXT
	, gl_LUMINANCE_ALPHA8I_EXT
	, gl_LUMINANCE_ALPHA8UI_EXT
	, gl_LUMINANCE_ALPHA_INTEGER_EXT
	, gl_LUMINANCE_INTEGER_EXT
	, gl_RED_INTEGER_EXT
	, gl_RGB16I_EXT
	, gl_RGB16UI_EXT
	, gl_RGB32I_EXT
	, gl_RGB32UI_EXT
	, gl_RGB8I_EXT
	, gl_RGB8UI_EXT
	, gl_RGBA16I_EXT
	, gl_RGBA16UI_EXT
	, gl_RGBA32I_EXT
	, gl_RGBA32UI_EXT
	, gl_RGBA8I_EXT
	, gl_RGBA8UI_EXT
	, gl_RGBA_INTEGER_EXT
	, gl_RGBA_INTEGER_MODE_EXT
	, gl_RGB_INTEGER_EXT
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

import Graphics.OpenGL.Internal.Shared

gl_EXT_texture_integer :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_EXT_texture_integer = extGL 362

glClearColorIiEXT :: (MonadIO m, MonadReader e m, HasScope e) => GLint -> GLint -> GLint -> GLint -> m ()
glClearColorIiEXT v0 v1 v2 v3 = funGL 1377 >>= \f -> liftIO $ f v0 v1 v2 v3

glClearColorIuiEXT :: (MonadIO m, MonadReader e m, HasScope e) => GLuint -> GLuint -> GLuint -> GLuint -> m ()
glClearColorIuiEXT v0 v1 v2 v3 = funGL 1378 >>= \f -> liftIO $ f v0 v1 v2 v3

gl_ALPHA16I_EXT :: GLenum
gl_ALPHA16I_EXT = 0x8D8A

gl_ALPHA16UI_EXT :: GLenum
gl_ALPHA16UI_EXT = 0x8D78

gl_ALPHA32I_EXT :: GLenum
gl_ALPHA32I_EXT = 0x8D84

gl_ALPHA32UI_EXT :: GLenum
gl_ALPHA32UI_EXT = 0x8D72

gl_ALPHA8I_EXT :: GLenum
gl_ALPHA8I_EXT = 0x8D90

gl_ALPHA8UI_EXT :: GLenum
gl_ALPHA8UI_EXT = 0x8D7E

gl_ALPHA_INTEGER_EXT :: GLenum
gl_ALPHA_INTEGER_EXT = 0x8D97

gl_BGRA_INTEGER_EXT :: GLenum
gl_BGRA_INTEGER_EXT = 0x8D9B

gl_BGR_INTEGER_EXT :: GLenum
gl_BGR_INTEGER_EXT = 0x8D9A

gl_BLUE_INTEGER_EXT :: GLenum
gl_BLUE_INTEGER_EXT = 0x8D96

gl_GREEN_INTEGER_EXT :: GLenum
gl_GREEN_INTEGER_EXT = 0x8D95

gl_INTENSITY16I_EXT :: GLenum
gl_INTENSITY16I_EXT = 0x8D8B

gl_INTENSITY16UI_EXT :: GLenum
gl_INTENSITY16UI_EXT = 0x8D79

gl_INTENSITY32I_EXT :: GLenum
gl_INTENSITY32I_EXT = 0x8D85

gl_INTENSITY32UI_EXT :: GLenum
gl_INTENSITY32UI_EXT = 0x8D73

gl_INTENSITY8I_EXT :: GLenum
gl_INTENSITY8I_EXT = 0x8D91

gl_INTENSITY8UI_EXT :: GLenum
gl_INTENSITY8UI_EXT = 0x8D7F

gl_LUMINANCE16I_EXT :: GLenum
gl_LUMINANCE16I_EXT = 0x8D8C

gl_LUMINANCE16UI_EXT :: GLenum
gl_LUMINANCE16UI_EXT = 0x8D7A

gl_LUMINANCE32I_EXT :: GLenum
gl_LUMINANCE32I_EXT = 0x8D86

gl_LUMINANCE32UI_EXT :: GLenum
gl_LUMINANCE32UI_EXT = 0x8D74

gl_LUMINANCE8I_EXT :: GLenum
gl_LUMINANCE8I_EXT = 0x8D92

gl_LUMINANCE8UI_EXT :: GLenum
gl_LUMINANCE8UI_EXT = 0x8D80

gl_LUMINANCE_ALPHA16I_EXT :: GLenum
gl_LUMINANCE_ALPHA16I_EXT = 0x8D8D

gl_LUMINANCE_ALPHA16UI_EXT :: GLenum
gl_LUMINANCE_ALPHA16UI_EXT = 0x8D7B

gl_LUMINANCE_ALPHA32I_EXT :: GLenum
gl_LUMINANCE_ALPHA32I_EXT = 0x8D87

gl_LUMINANCE_ALPHA32UI_EXT :: GLenum
gl_LUMINANCE_ALPHA32UI_EXT = 0x8D75

gl_LUMINANCE_ALPHA8I_EXT :: GLenum
gl_LUMINANCE_ALPHA8I_EXT = 0x8D93

gl_LUMINANCE_ALPHA8UI_EXT :: GLenum
gl_LUMINANCE_ALPHA8UI_EXT = 0x8D81

gl_LUMINANCE_ALPHA_INTEGER_EXT :: GLenum
gl_LUMINANCE_ALPHA_INTEGER_EXT = 0x8D9D

gl_LUMINANCE_INTEGER_EXT :: GLenum
gl_LUMINANCE_INTEGER_EXT = 0x8D9C

gl_RED_INTEGER_EXT :: GLenum
gl_RED_INTEGER_EXT = 0x8D94

gl_RGB16I_EXT :: GLenum
gl_RGB16I_EXT = 0x8D89

gl_RGB16UI_EXT :: GLenum
gl_RGB16UI_EXT = 0x8D77

gl_RGB32I_EXT :: GLenum
gl_RGB32I_EXT = 0x8D83

gl_RGB32UI_EXT :: GLenum
gl_RGB32UI_EXT = 0x8D71

gl_RGB8I_EXT :: GLenum
gl_RGB8I_EXT = 0x8D8F

gl_RGB8UI_EXT :: GLenum
gl_RGB8UI_EXT = 0x8D7D

gl_RGBA16I_EXT :: GLenum
gl_RGBA16I_EXT = 0x8D88

gl_RGBA16UI_EXT :: GLenum
gl_RGBA16UI_EXT = 0x8D76

gl_RGBA32I_EXT :: GLenum
gl_RGBA32I_EXT = 0x8D82

gl_RGBA32UI_EXT :: GLenum
gl_RGBA32UI_EXT = 0x8D70

gl_RGBA8I_EXT :: GLenum
gl_RGBA8I_EXT = 0x8D8E

gl_RGBA8UI_EXT :: GLenum
gl_RGBA8UI_EXT = 0x8D7C

gl_RGBA_INTEGER_EXT :: GLenum
gl_RGBA_INTEGER_EXT = 0x8D99

gl_RGBA_INTEGER_MODE_EXT :: GLenum
gl_RGBA_INTEGER_MODE_EXT = 0x8D9E

gl_RGB_INTEGER_EXT :: GLenum
gl_RGB_INTEGER_EXT = 0x8D98