-- This file was automatically generated.
module Graphics.OpenGL.Extension.EXT.Texture (
	-- * Extension Support
	  gl_EXT_texture

	-- * GL_EXT_texture
	, gl_ALPHA12_EXT
	, gl_ALPHA16_EXT
	, gl_ALPHA4_EXT
	, gl_ALPHA8_EXT
	, gl_INTENSITY12_EXT
	, gl_INTENSITY16_EXT
	, gl_INTENSITY4_EXT
	, gl_INTENSITY8_EXT
	, gl_INTENSITY_EXT
	, gl_LUMINANCE12_ALPHA12_EXT
	, gl_LUMINANCE12_ALPHA4_EXT
	, gl_LUMINANCE12_EXT
	, gl_LUMINANCE16_ALPHA16_EXT
	, gl_LUMINANCE16_EXT
	, gl_LUMINANCE4_ALPHA4_EXT
	, gl_LUMINANCE4_EXT
	, gl_LUMINANCE6_ALPHA2_EXT
	, gl_LUMINANCE8_ALPHA8_EXT
	, gl_LUMINANCE8_EXT
	, gl_PROXY_TEXTURE_1D_EXT
	, gl_PROXY_TEXTURE_2D_EXT
	, gl_REPLACE_EXT
	, gl_RGB10_A2_EXT
	, gl_RGB10_EXT
	, gl_RGB12_EXT
	, gl_RGB16_EXT
	, gl_RGB2_EXT
	, gl_RGB4_EXT
	, gl_RGB5_A1_EXT
	, gl_RGB5_EXT
	, gl_RGB8_EXT
	, gl_RGBA12_EXT
	, gl_RGBA16_EXT
	, gl_RGBA2_EXT
	, gl_RGBA4_EXT
	, gl_RGBA8_EXT
	, gl_TEXTURE_ALPHA_SIZE_EXT
	, gl_TEXTURE_BLUE_SIZE_EXT
	, gl_TEXTURE_GREEN_SIZE_EXT
	, gl_TEXTURE_INTENSITY_SIZE_EXT
	, gl_TEXTURE_LUMINANCE_SIZE_EXT
	, gl_TEXTURE_RED_SIZE_EXT
	, gl_TEXTURE_TOO_LARGE_EXT
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

import Graphics.OpenGL.Internal.Shared

gl_EXT_texture :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_EXT_texture = extGL 344

gl_ALPHA12_EXT :: GLenum
gl_ALPHA12_EXT = 0x803D

gl_ALPHA16_EXT :: GLenum
gl_ALPHA16_EXT = 0x803E

gl_ALPHA4_EXT :: GLenum
gl_ALPHA4_EXT = 0x803B

gl_INTENSITY12_EXT :: GLenum
gl_INTENSITY12_EXT = 0x804C

gl_INTENSITY16_EXT :: GLenum
gl_INTENSITY16_EXT = 0x804D

gl_INTENSITY4_EXT :: GLenum
gl_INTENSITY4_EXT = 0x804A

gl_INTENSITY8_EXT :: GLenum
gl_INTENSITY8_EXT = 0x804B

gl_INTENSITY_EXT :: GLenum
gl_INTENSITY_EXT = 0x8049

gl_LUMINANCE12_ALPHA12_EXT :: GLenum
gl_LUMINANCE12_ALPHA12_EXT = 0x8047

gl_LUMINANCE12_ALPHA4_EXT :: GLenum
gl_LUMINANCE12_ALPHA4_EXT = 0x8046

gl_LUMINANCE12_EXT :: GLenum
gl_LUMINANCE12_EXT = 0x8041

gl_LUMINANCE16_ALPHA16_EXT :: GLenum
gl_LUMINANCE16_ALPHA16_EXT = 0x8048

gl_LUMINANCE16_EXT :: GLenum
gl_LUMINANCE16_EXT = 0x8042

gl_LUMINANCE4_ALPHA4_EXT :: GLenum
gl_LUMINANCE4_ALPHA4_EXT = 0x8043

gl_LUMINANCE4_EXT :: GLenum
gl_LUMINANCE4_EXT = 0x803F

gl_LUMINANCE6_ALPHA2_EXT :: GLenum
gl_LUMINANCE6_ALPHA2_EXT = 0x8044

gl_PROXY_TEXTURE_1D_EXT :: GLenum
gl_PROXY_TEXTURE_1D_EXT = 0x8063

gl_PROXY_TEXTURE_2D_EXT :: GLenum
gl_PROXY_TEXTURE_2D_EXT = 0x8064

gl_REPLACE_EXT :: GLenum
gl_REPLACE_EXT = 0x8062

gl_RGB12_EXT :: GLenum
gl_RGB12_EXT = 0x8053

gl_RGB16_EXT :: GLenum
gl_RGB16_EXT = 0x8054

gl_RGB2_EXT :: GLenum
gl_RGB2_EXT = 0x804E

gl_RGB4_EXT :: GLenum
gl_RGB4_EXT = 0x804F

gl_RGB5_A1_EXT :: GLenum
gl_RGB5_A1_EXT = 0x8057

gl_RGB5_EXT :: GLenum
gl_RGB5_EXT = 0x8050

gl_RGB8_EXT :: GLenum
gl_RGB8_EXT = 0x8051

gl_RGBA12_EXT :: GLenum
gl_RGBA12_EXT = 0x805A

gl_RGBA16_EXT :: GLenum
gl_RGBA16_EXT = 0x805B

gl_RGBA2_EXT :: GLenum
gl_RGBA2_EXT = 0x8055

gl_RGBA4_EXT :: GLenum
gl_RGBA4_EXT = 0x8056

gl_RGBA8_EXT :: GLenum
gl_RGBA8_EXT = 0x8058

gl_TEXTURE_ALPHA_SIZE_EXT :: GLenum
gl_TEXTURE_ALPHA_SIZE_EXT = 0x805F

gl_TEXTURE_BLUE_SIZE_EXT :: GLenum
gl_TEXTURE_BLUE_SIZE_EXT = 0x805E

gl_TEXTURE_GREEN_SIZE_EXT :: GLenum
gl_TEXTURE_GREEN_SIZE_EXT = 0x805D

gl_TEXTURE_INTENSITY_SIZE_EXT :: GLenum
gl_TEXTURE_INTENSITY_SIZE_EXT = 0x8061

gl_TEXTURE_LUMINANCE_SIZE_EXT :: GLenum
gl_TEXTURE_LUMINANCE_SIZE_EXT = 0x8060

gl_TEXTURE_RED_SIZE_EXT :: GLenum
gl_TEXTURE_RED_SIZE_EXT = 0x805C

gl_TEXTURE_TOO_LARGE_EXT :: GLenum
gl_TEXTURE_TOO_LARGE_EXT = 0x8065