-- This file was automatically generated.
module Graphics.OpenGL.Extension.EXT.TextureCubeMap (
	-- * Extension Support
	  gl_EXT_texture_cube_map

	-- * GL_EXT_texture_cube_map
	, gl_MAX_CUBE_MAP_TEXTURE_SIZE_EXT
	, gl_NORMAL_MAP_EXT
	, gl_PROXY_TEXTURE_CUBE_MAP_EXT
	, gl_REFLECTION_MAP_EXT
	, gl_TEXTURE_BINDING_CUBE_MAP_EXT
	, gl_TEXTURE_CUBE_MAP_EXT
	, gl_TEXTURE_CUBE_MAP_NEGATIVE_X_EXT
	, gl_TEXTURE_CUBE_MAP_NEGATIVE_Y_EXT
	, gl_TEXTURE_CUBE_MAP_NEGATIVE_Z_EXT
	, gl_TEXTURE_CUBE_MAP_POSITIVE_X_EXT
	, gl_TEXTURE_CUBE_MAP_POSITIVE_Y_EXT
	, gl_TEXTURE_CUBE_MAP_POSITIVE_Z_EXT
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

gl_EXT_texture_cube_map :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_EXT_texture_cube_map = extGL 354

gl_MAX_CUBE_MAP_TEXTURE_SIZE_EXT :: GLenum
gl_MAX_CUBE_MAP_TEXTURE_SIZE_EXT = 0x851C

gl_NORMAL_MAP_EXT :: GLenum
gl_NORMAL_MAP_EXT = 0x8511

gl_PROXY_TEXTURE_CUBE_MAP_EXT :: GLenum
gl_PROXY_TEXTURE_CUBE_MAP_EXT = 0x851B

gl_REFLECTION_MAP_EXT :: GLenum
gl_REFLECTION_MAP_EXT = 0x8512

gl_TEXTURE_BINDING_CUBE_MAP_EXT :: GLenum
gl_TEXTURE_BINDING_CUBE_MAP_EXT = 0x8514

gl_TEXTURE_CUBE_MAP_EXT :: GLenum
gl_TEXTURE_CUBE_MAP_EXT = 0x8513

gl_TEXTURE_CUBE_MAP_NEGATIVE_X_EXT :: GLenum
gl_TEXTURE_CUBE_MAP_NEGATIVE_X_EXT = 0x8516

gl_TEXTURE_CUBE_MAP_NEGATIVE_Y_EXT :: GLenum
gl_TEXTURE_CUBE_MAP_NEGATIVE_Y_EXT = 0x8518

gl_TEXTURE_CUBE_MAP_NEGATIVE_Z_EXT :: GLenum
gl_TEXTURE_CUBE_MAP_NEGATIVE_Z_EXT = 0x851A

gl_TEXTURE_CUBE_MAP_POSITIVE_X_EXT :: GLenum
gl_TEXTURE_CUBE_MAP_POSITIVE_X_EXT = 0x8515

gl_TEXTURE_CUBE_MAP_POSITIVE_Y_EXT :: GLenum
gl_TEXTURE_CUBE_MAP_POSITIVE_Y_EXT = 0x8517

gl_TEXTURE_CUBE_MAP_POSITIVE_Z_EXT :: GLenum
gl_TEXTURE_CUBE_MAP_POSITIVE_Z_EXT = 0x8519