-- This file was automatically generated.
module Graphics.OpenGL.Extension.EXT.TextureSRGB (
	-- * Extension Support
	  gl_EXT_texture_sRGB

	-- * GL_EXT_texture_sRGB
	, gl_COMPRESSED_SLUMINANCE_ALPHA_EXT
	, gl_COMPRESSED_SLUMINANCE_EXT
	, gl_COMPRESSED_SRGB_ALPHA_EXT
	, gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT
	, gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT
	, gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT
	, gl_COMPRESSED_SRGB_EXT
	, gl_COMPRESSED_SRGB_S3TC_DXT1_EXT
	, gl_SLUMINANCE8_ALPHA8_EXT
	, gl_SLUMINANCE8_EXT
	, gl_SLUMINANCE_ALPHA_EXT
	, gl_SLUMINANCE_EXT
	, gl_SRGB8_ALPHA8_EXT
	, gl_SRGB8_EXT
	, gl_SRGB_ALPHA_EXT
	, gl_SRGB_EXT
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

import Graphics.OpenGL.Internal.Shared

gl_EXT_texture_sRGB :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_EXT_texture_sRGB = extGL 368

gl_COMPRESSED_SLUMINANCE_ALPHA_EXT :: GLenum
gl_COMPRESSED_SLUMINANCE_ALPHA_EXT = 0x8C4B

gl_COMPRESSED_SLUMINANCE_EXT :: GLenum
gl_COMPRESSED_SLUMINANCE_EXT = 0x8C4A

gl_COMPRESSED_SRGB_ALPHA_EXT :: GLenum
gl_COMPRESSED_SRGB_ALPHA_EXT = 0x8C49

gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT :: GLenum
gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT = 0x8C4D

gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT :: GLenum
gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT = 0x8C4E

gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT :: GLenum
gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT = 0x8C4F

gl_COMPRESSED_SRGB_EXT :: GLenum
gl_COMPRESSED_SRGB_EXT = 0x8C48

gl_COMPRESSED_SRGB_S3TC_DXT1_EXT :: GLenum
gl_COMPRESSED_SRGB_S3TC_DXT1_EXT = 0x8C4C

gl_SLUMINANCE8_ALPHA8_EXT :: GLenum
gl_SLUMINANCE8_ALPHA8_EXT = 0x8C45

gl_SLUMINANCE8_EXT :: GLenum
gl_SLUMINANCE8_EXT = 0x8C47

gl_SLUMINANCE_ALPHA_EXT :: GLenum
gl_SLUMINANCE_ALPHA_EXT = 0x8C44

gl_SLUMINANCE_EXT :: GLenum
gl_SLUMINANCE_EXT = 0x8C46

gl_SRGB8_EXT :: GLenum
gl_SRGB8_EXT = 0x8C41