-- This file was automatically generated.
module Graphics.OpenGL.Extension.PGI.MiscHints (
	-- * Extension Support
	  gl_PGI_misc_hints

	-- * GL_PGI_misc_hints
	, glHintPGI
	, gl_ALLOW_DRAW_FRG_HINT_PGI
	, gl_ALLOW_DRAW_MEM_HINT_PGI
	, gl_ALLOW_DRAW_OBJ_HINT_PGI
	, gl_ALLOW_DRAW_WIN_HINT_PGI
	, gl_ALWAYS_FAST_HINT_PGI
	, gl_ALWAYS_SOFT_HINT_PGI
	, gl_BACK_NORMALS_HINT_PGI
	, gl_CLIP_FAR_HINT_PGI
	, gl_CLIP_NEAR_HINT_PGI
	, gl_CONSERVE_MEMORY_HINT_PGI
	, gl_FULL_STIPPLE_HINT_PGI
	, gl_NATIVE_GRAPHICS_BEGIN_HINT_PGI
	, gl_NATIVE_GRAPHICS_END_HINT_PGI
	, gl_NATIVE_GRAPHICS_HANDLE_PGI
	, gl_PREFER_DOUBLEBUFFER_HINT_PGI
	, gl_RECLAIM_MEMORY_HINT_PGI
	, gl_STRICT_DEPTHFUNC_HINT_PGI
	, gl_STRICT_LIGHTING_HINT_PGI
	, gl_STRICT_SCISSOR_HINT_PGI
	, gl_WIDE_LINE_HINT_PGI
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

gl_PGI_misc_hints :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_PGI_misc_hints = extGL 601

glHintPGI :: (MonadIO m, MonadReader e m, HasScope e) => GLenum -> GLint -> m ()
glHintPGI v0 v1 = funGL 2181 >>= \f -> liftIO $ f v0 v1

gl_ALLOW_DRAW_FRG_HINT_PGI :: GLenum
gl_ALLOW_DRAW_FRG_HINT_PGI = 0x1A210

gl_ALLOW_DRAW_MEM_HINT_PGI :: GLenum
gl_ALLOW_DRAW_MEM_HINT_PGI = 0x1A211

gl_ALLOW_DRAW_OBJ_HINT_PGI :: GLenum
gl_ALLOW_DRAW_OBJ_HINT_PGI = 0x1A20E

gl_ALLOW_DRAW_WIN_HINT_PGI :: GLenum
gl_ALLOW_DRAW_WIN_HINT_PGI = 0x1A20F

gl_ALWAYS_FAST_HINT_PGI :: GLenum
gl_ALWAYS_FAST_HINT_PGI = 0x1A20C

gl_ALWAYS_SOFT_HINT_PGI :: GLenum
gl_ALWAYS_SOFT_HINT_PGI = 0x1A20D

gl_BACK_NORMALS_HINT_PGI :: GLenum
gl_BACK_NORMALS_HINT_PGI = 0x1A223

gl_CLIP_FAR_HINT_PGI :: GLenum
gl_CLIP_FAR_HINT_PGI = 0x1A221

gl_CLIP_NEAR_HINT_PGI :: GLenum
gl_CLIP_NEAR_HINT_PGI = 0x1A220

gl_CONSERVE_MEMORY_HINT_PGI :: GLenum
gl_CONSERVE_MEMORY_HINT_PGI = 0x1A1FD

gl_FULL_STIPPLE_HINT_PGI :: GLenum
gl_FULL_STIPPLE_HINT_PGI = 0x1A219

gl_NATIVE_GRAPHICS_BEGIN_HINT_PGI :: GLenum
gl_NATIVE_GRAPHICS_BEGIN_HINT_PGI = 0x1A203

gl_NATIVE_GRAPHICS_END_HINT_PGI :: GLenum
gl_NATIVE_GRAPHICS_END_HINT_PGI = 0x1A204

gl_NATIVE_GRAPHICS_HANDLE_PGI :: GLenum
gl_NATIVE_GRAPHICS_HANDLE_PGI = 0x1A202

gl_PREFER_DOUBLEBUFFER_HINT_PGI :: GLenum
gl_PREFER_DOUBLEBUFFER_HINT_PGI = 0x1A1F8

gl_RECLAIM_MEMORY_HINT_PGI :: GLenum
gl_RECLAIM_MEMORY_HINT_PGI = 0x1A1FE

gl_STRICT_DEPTHFUNC_HINT_PGI :: GLenum
gl_STRICT_DEPTHFUNC_HINT_PGI = 0x1A216

gl_STRICT_LIGHTING_HINT_PGI :: GLenum
gl_STRICT_LIGHTING_HINT_PGI = 0x1A217

gl_STRICT_SCISSOR_HINT_PGI :: GLenum
gl_STRICT_SCISSOR_HINT_PGI = 0x1A218

gl_WIDE_LINE_HINT_PGI :: GLenum
gl_WIDE_LINE_HINT_PGI = 0x1A222