-- This file was automatically generated.
module Graphics.OpenGL.Extension.PGI.VertexHints (
	-- * Extension Support
	  gl_PGI_vertex_hints

	-- * GL_PGI_vertex_hints
	, gl_COLOR3_BIT_PGI
	, gl_COLOR4_BIT_PGI
	, gl_EDGEFLAG_BIT_PGI
	, gl_INDEX_BIT_PGI
	, gl_MATERIAL_SIDE_HINT_PGI
	, gl_MAT_AMBIENT_AND_DIFFUSE_BIT_PGI
	, gl_MAT_AMBIENT_BIT_PGI
	, gl_MAT_COLOR_INDEXES_BIT_PGI
	, gl_MAT_DIFFUSE_BIT_PGI
	, gl_MAT_EMISSION_BIT_PGI
	, gl_MAT_SHININESS_BIT_PGI
	, gl_MAT_SPECULAR_BIT_PGI
	, gl_MAX_VERTEX_HINT_PGI
	, gl_NORMAL_BIT_PGI
	, gl_TEXCOORD1_BIT_PGI
	, gl_TEXCOORD2_BIT_PGI
	, gl_TEXCOORD3_BIT_PGI
	, gl_TEXCOORD4_BIT_PGI
	, gl_VERTEX23_BIT_PGI
	, gl_VERTEX4_BIT_PGI
	, gl_VERTEX_CONSISTENT_HINT_PGI
	, gl_VERTEX_DATA_HINT_PGI
) where

import Graphics.OpenGL.Internal.Scope
import Graphics.OpenGL.Basic

gl_PGI_vertex_hints :: (Monad m, MonadReader e m, HasScope e) => m Bool
gl_PGI_vertex_hints = extGL 602

gl_COLOR3_BIT_PGI :: GLenum
gl_COLOR3_BIT_PGI = 0x00010000

gl_COLOR4_BIT_PGI :: GLenum
gl_COLOR4_BIT_PGI = 0x00020000

gl_EDGEFLAG_BIT_PGI :: GLenum
gl_EDGEFLAG_BIT_PGI = 0x00040000

gl_INDEX_BIT_PGI :: GLenum
gl_INDEX_BIT_PGI = 0x00080000

gl_MATERIAL_SIDE_HINT_PGI :: GLenum
gl_MATERIAL_SIDE_HINT_PGI = 0x1A22C

gl_MAT_AMBIENT_AND_DIFFUSE_BIT_PGI :: GLenum
gl_MAT_AMBIENT_AND_DIFFUSE_BIT_PGI = 0x00200000

gl_MAT_AMBIENT_BIT_PGI :: GLenum
gl_MAT_AMBIENT_BIT_PGI = 0x00100000

gl_MAT_COLOR_INDEXES_BIT_PGI :: GLenum
gl_MAT_COLOR_INDEXES_BIT_PGI = 0x01000000

gl_MAT_DIFFUSE_BIT_PGI :: GLenum
gl_MAT_DIFFUSE_BIT_PGI = 0x00400000

gl_MAT_EMISSION_BIT_PGI :: GLenum
gl_MAT_EMISSION_BIT_PGI = 0x00800000

gl_MAT_SHININESS_BIT_PGI :: GLenum
gl_MAT_SHININESS_BIT_PGI = 0x02000000

gl_MAT_SPECULAR_BIT_PGI :: GLenum
gl_MAT_SPECULAR_BIT_PGI = 0x04000000

gl_MAX_VERTEX_HINT_PGI :: GLenum
gl_MAX_VERTEX_HINT_PGI = 0x1A22D

gl_NORMAL_BIT_PGI :: GLenum
gl_NORMAL_BIT_PGI = 0x08000000

gl_TEXCOORD1_BIT_PGI :: GLenum
gl_TEXCOORD1_BIT_PGI = 0x10000000

gl_TEXCOORD2_BIT_PGI :: GLenum
gl_TEXCOORD2_BIT_PGI = 0x20000000

gl_TEXCOORD3_BIT_PGI :: GLenum
gl_TEXCOORD3_BIT_PGI = 0x40000000

gl_TEXCOORD4_BIT_PGI :: GLenum
gl_TEXCOORD4_BIT_PGI = 0x80000000

gl_VERTEX23_BIT_PGI :: GLenum
gl_VERTEX23_BIT_PGI = 0x00000004

gl_VERTEX4_BIT_PGI :: GLenum
gl_VERTEX4_BIT_PGI = 0x00000008

gl_VERTEX_CONSISTENT_HINT_PGI :: GLenum
gl_VERTEX_CONSISTENT_HINT_PGI = 0x1A22B

gl_VERTEX_DATA_HINT_PGI :: GLenum
gl_VERTEX_DATA_HINT_PGI = 0x1A22A